= 管理项目
:proglang: Motoko
:IC: 互联网计算机区块链
:company-id: DFINITY

您可以通过修改每个项目的 `+dfx.json+` 配置文件来修改个别项目的一些关键设置。
您可以使用 `+dfx config+` 命令以编程方式更改这些设置或直接手动编辑 `+dfx.json+` 文件。

== 如何更改源目录

在使用 `+dfx build+` 命令为项目编译源代码之前，您可能需要检查存储 dapp 源代码的默认位置。
默认情况下，您创建新项目使用的名称是一个容器智能合约（`+canister_name+`）和一个资产容器（`+canister_name_assets+`）的名称，dapp源代码预计在`+ src/canister_name+` 目录。 同样，前端源代码的默认位置在 `+src/canister_name_assets/src+` 目录中，前端输出位于 `+dist/canister_name_assets+` 目录中。

但是，根据 dapp 的复杂性和架构，您可能需要修改 dapp 源代码、前端源代码或前端输出的默认位置。

例如，对于一个简单的 dapp，您可能希望删除一个目录级别并将源代码放在 `+src+` 目录中:

[source,text]
----
  "main": "src/main.mo",
----

对于更复杂的 dapp，您可能希望使用多层目录结构:

[source,text]
----
"canisters": {
  "profiles": {
    "main": "src/profiles/utils/main.mo"
  },
  "events": {
    "main": "src/events/calendar/main.mo"
  },
  "media": {
    "main": "src/events/reports/main.mo"
  }
}
----

注意:如果您修改源代码目录的默认设置，请确保 `+dfx.json+` 配置文件中的设置与文件系统上的目录位置匹配。
////
== 如何更改输出目录

当您使用 `+dfx build+` 命令为项目编译源代码时，该命令会自动在默认输出文件夹中生成 WebAssembly 可执行文件和接口绑定。
您可以通过修改项目的本地 `+dfx.json+` 配置文件来自定义项目的默认输出文件夹。
您可以通过编辑文件手动更改 `+dfx.json+` 配置文件中的设置，也可以通过运行 `+dfx config+` 命令以编程方式更改设置。

要查看您当前使用的默认输出文件夹，请运行以下命令:

[source,bash]
----
dfx config defaults.build.output
----

该命令返回您当前在 `+dfx.json+` 配置文件中定义的设置。
例如:

[source,bash]
----
"canisters/"
----

要更改默认输出文件夹，请运行 `+dfx config+` 命令并指定一个新位置。
例如，要将默认输出目录从 `+canisters+` 更改为 `+ready_for_release+`，请运行以下命令:

[source,bash]
----
dfx config defaults.build.output ready_for_release
----

此命令将 `+dfx.json` 配置文件中的 `+output+` 设置更改为 `+ready for release`。

例如:

[source,json]
----
  "defaults": {
    "build": {
      "output": "ready_for_release"
----
////

== 如何更改主 dapp 文件名

在使用 `+dfx build+` 命令为项目编译源代码之前，您应该验证用于 dapp 源代码的位置和文件名。

例如，如果你想为 `+factorial+` dapp 构建一个容器智能合约，并且 dapp 的源代码位于 `+src/math/factorial.mo+`，你应该确保你有正确的路径 在配置文件的 `+canisters+` 部分中为 `+main+` 设置指定。

例如:

[source,json]
----
"main": "src/math/factorial.mo",
----

请记住，更改 dapp 文件名的配置设置只会影响 `+dfx build+` 命令查找要编译的源代码的位置。 在配置文件中进行更改不会重命名文件系统上的任何文件或目录。
如果您更改主 dapp 文件的路径或文件本身的名称，请务必更改项目目录中的名称和位置。

== 如何更改服务 dapp 前端的位置

您可以通过修改 `+dfx.json+` 配置文件中的本地网络设置来更改为 dapp 前端提供服务的默认主机名和端口号。

例如，您可以通过修改 `+bind+` 设置来更改本地网络的 IP 地址:

[source,json]
----
"networks": {
  "local": {
    "bind": "192.168.47.1:8000",
    "type": "ephemeral"
  }
}
----
