= 词汇表
:proglang: Motoko
:IC: 互联网计算机
:company-id: DFINITY

[[g-actor]]
actor::
  Actor 是现代编程语言中的一种特殊对象，它以隔离状态处理消息，使它们能够被远程和异步处理。

[[g-canister]]
容器智能合约::
  容器智能合约，有时也简称为容器，是智能合约的扩展形式。 它们是革命性的，因为它们可以确定地并行运行。 这是通过依赖actor模型和确定性消息传递来实现的。 容器智能合约具有通用唯一标识符和定义特定 dapp 边界的所有者。
   容器封装了所有编程逻辑、公共入口方法、所提供消息类型的接口描述以及它所描述的 dapp 的状态信息。

[[g-principal]]
principal::
  principal是可以通过 {IC} 区块链进行身份验证的实体。 与 {IC} 区块链交互的principal通常通过身份进行交互。 例如，第一次使用 {sdk-short-name} 时，`+dfx+` 命令行工具会使用 PEM 文件中的公钥/私钥对为您创建一个 `+default+` 开发者身份。 这个开发者身份决定了一个**principal**。 有一个主体的文本表示，通常称为您的**主体标识符**。
   请注意，开发人员身份还可用于派生**帐户标识符**（类似于比特币或以太坊地址），以代表身份将 ICP 令牌保存在帐本容器中。

[[g-controller]]
控制器::
  控制器是具有特殊权限来管理其控制的容器智能合约的主体。
  例如，只有控制主体可用于安装、升级或删除其控制下的容器。
  您可以使用与用户或容器相关联的主体（通常称为主体标识符）的文本表示来指定控制器主体。

[[g-ledger]]
账本::
  {IC} 区块链将所有涉及 ICP 代币的交易记录在一个专门的管理容器智能合约中，称为 **ledger canister**。
  账本容器实现了一个智能合约，该合约维护**帐户**和**余额**，并保留影响帐户和余额的*交易*的历史记录。 记录交易以跟踪以下特定事件:
  
* **Mint ICP 代币** 用于帐户。
* **将 ICP 代币**从一个账户转移到另一个账户。
* **燃烧 ICP 代币**以消除它们的存在。

[[g-wallet]]
wallet::
  钱包是允许存储和管理燃料费的专用 dapp（实现为容器智能合约）。 燃料费用于支付 {IC} 区块链上的计算和资源消耗。 Cycles可以通过从{IC}区块链的原生实用代币ICP转换获得。

[[g-node]]
节点::
  托管参与 {IC} 区块链所需的所有硬件、副本软件和配置设置的物理机或虚拟机。

[[g-replica]]
副本:: 
  在 {IC} 区块链的上下文中，副本是指在节点上运行的 {IC} 协议进程。

[[g-wasm]]
WebAssembly::
  https://webassembly.org/[WebAssembly] (`+Wasm+`) 是一种低级计算机指令格式。
   由于 WebAssembly 定义了一种可移植的、开放标准的二进制格式，可以清晰地抽象出大多数现代计算机硬件，因此它广泛支持在 Internet 上运行的程序。
   用 {proglang} 编写的 Dapp 被编译为 WebAssembly 代码，以便在 {IC} 区块链上执行。