= 语言服务器和开发客户端支持
2019 年 12 月（阿尔法 3）
ifdef::env-github,env-browser[:outfilesuffix:.adoc]
:toc-title: 开发客户
:toclevels: 1
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY

https://microsoft.github.io/language-server-protocol[Language Server Protocol (LSP)]——最初由 Microsoft 开发——提供了一种通用语言来添加广泛有用的功能，如自动代码完成、GoTo 定义和悬停 -over 工具提示到开发工具。
使用语言服务器协议，语言服务器可以在编程语言和任何编辑器、集成开发环境 (IDE) 或客户端端点工具之间实现标准化的进程间通信。

由于语言服务器协议 (LSP) 对特定语言服务器和开发工具如何通信的协议进行了标准化，因此单个语言服务器可以轻松地在多个开发工具中重复使用。

== 为 {proglang} 添加语言服务器

使用 {sdk-short-name}，您可以通过在编辑器或开发中打开 {proglang} 程序时以编程方式调用 `+dfx _language-service+` 来将 {proglang} 的语言服务器添加到您的编辑器或开发环境客户端 环境配置为识别语言服务器。
您可以使用任何支持语言服务器协议的编辑器或集成开发环境以编程方式调用`+dfx _language-service+`。一旦被调用，语言服务器会确保您的开发环境报告 {proglang} 编译器错误并提供代码完成和重构工具。

例如，如果您使用 Visual Studio Code (VSCode) 或 Emacs 作为开发环境，您可以安装插件扩展，使这些编辑器能够自动调用 {proglang} 语言服务器。

注意:目前只有 Visual Studio Code (VSCode) 插件扩展可用于 {proglang}。
有关安装插件的信息，请参见链接:../quickstart/local-quickstart{outfilesuffix}#install-vscode[安装语言编辑器插件]。

== 手动调用语言服务

尽管在终端 shell 中直接启动 {proglang} 语言服务器是非常罕见的。可以通过运行以下命令来做到这一点:

[source,bash,subs="quotes"]
----
dfx _language-service --force-tty
----

请注意，您只能从项目目录中运行此命令。
例如，如果您的项目名称是 `+hello_world+`，那么您当前的工作目录必须是 `+hello_world+` 顶级项目目录或其子目录之一。

=== 基本用法

[source,bash,subs="quotes"]
----
dfx _language-service [canister_name] [flag] 
----

=== 标志

您可以在 `+dfx _language-service+` 命令中使用以下可选标志。

[cols="<,<",options="header",]
|===
|标志 |说明
|`+--force-tty+` |直接在终端shell中启动{proglang}语言服务器。

|`+-h+`, `+--help+` |显示使用信息。

|`+-V+`, `+--version+` |显示版本信息。
|===

=== 参数

您可以为 `+dfx _language-service+` 命令指定以下参数。

[width="100%",cols="<36%,<64%",options="header",]
|===
|参数 |描述
|`+canister_name+` |指定编译器应该监视的容器的名称。
如果您指定容器名称，该名称应与您在项目的 `+dfx.json+` 配置文件中配置的容器名称匹配。
如果不指定容器名称，则使用 `+dfx.json+` 配置文件中指定的第一个容器作为目标。
|===

=== 例子

如果你想使用集成开发环境为容器`+my-canister+`开发代码，你应该让开发环境使用以下`+dfx _language-service+`命令调用语言服务:
[source,bash]
----
dfx _language-service my-canister
----
