:title:  {IC} SDK - Developer Tools
= 开发者中心
:proglang: Motoko
:IC: 互联网计算机
:company-id: DFINITY
:page-layout: home
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

{IC} 区块链准备帮助您以一种新的方式来设计、构建和发布 dapps。

== 开发 dapp

{IC} 是运行容器智能合约的区块链，这些智能合约是将 WebAssembly 字节码和运行字节码的内存页面捆绑在一起的代码单元。{IC} 由并行运行的各个子网区块链组成，并通过使用 链密钥密码学。 这意味着运行在子网上的容器可以无缝调用托管在 {IC} 区块链的任何其他子网中的容器。 此外，{IC} 的治理系统可以通过添加新的子网来动态增加 {IC} 的容量，从而允许 dapp 横向扩展。

因此，开发人员可以构建由多个在不同子网上并行运行的容器组成的新 dapp，并可能将它们与已经在 {IC} 上运行的现有容器集成。

== 开发人员工作流程一览

在高层次上，开发在 {IC} 区块链上运行的 dapp 有两种可能的主要工作流程。

image:local-remote-path-workflow.svg[Development paths]

* *本地开发：*您在计算机上启动模拟 {IC} 区块链的本地容器执行环境。 然后您在本地执行环境中编写、编译、安装和迭代更新您的容器。 这使您可以在本地测试您的罐，而无需使用循环为其供电。

* *链上部署：* 一旦您的 dapp 准备就绪，您就可以将其部署到 {IC} 区块链主网，供全世界使用。 请注意，您的容器需要有燃料费才能在 {IC} 区块链主网上运行，如链接中所述link：../developers-guide/concepts/tokens-cycles{outfilesuffix}[代币和燃料费]。

无论您选择哪种开发工作流程，请记住，当您第一次部署容器时，无论是在本地执行环境还是在 {IC} 上，一个唯一的link：../developers-guide/glossary{outfilesuffix} #g-principal[principal identifier] 是为您的容器智能合约创建的。 例如，如果您开始在本地开发您的容器，然后将其部署到 {IC}，那么您的容器通常在本地执行环境和 {IC} 区块链主网上会有不同的标识符。 请注意，您也可以在部署新容器之前为新容器注册一个主体标识符，甚至在编写任何代码行之前。