= 下载中心
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

目前，您可以直接从本地计算机的终端shell中下载 {sdk-long-name}。
使用此安装选项，您可以以任何用户身份登录，无需其他软件。

// tag::install[] 
[[install-latest]]
== 直接从终端安装最新版本

要从终端 shell 下载和安装：

. 在本地计算机上打开终端 shell。
+
例如，在 macOS 上打开 Applications 文件夹，然后打开 Utilities 并双击 *Terminal*。

. 通过运行以下 `curl` 命令下载并安装 SDK 包：
+
[source,bash]
----
sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
----

[[install-version]]
== 从终端安装特定版本

如果要安装特定版本，例如，针对以前的版本进行测试，您可以修改安装命令以包含一个版本。

要从终端 shell 下载和安装特定版本：

. 在本地计算机上打开终端 shell。

. 将 `DFX_VERSION` 环境变量设置为要安装的 {sdk-short-name} 包的版本，作为 `+curl+` 命令的前缀。
+
例如，要安装 0.9.2 版，您将运行以下命令：
+
[source,bash]
----
DFX_VERSION=0.9.2 sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
----

注释：如果您使用 DFX_VERSION 环境变量安装尚未公开的 {sdk-short-name} 版本，请参阅此link:http-middleware{outfilesuffix}[article] 了解更改的概述。

// end::install[]   

== 下一步

有关后续步骤的信息，请参阅link:developers-guide/tutorials-intro{outfilesuffix}[Tutorials] 中的link:developers-guide/sdk-guide{outfilesuffix}[_SDK Developer Tools_]。

要在开始试验代码之前了解有关为 {IC} 编写程序的更多信息，请参阅link:developers-guide/concepts/concepts-intro{outfilesuffix}[Concepts]。

有关使用 {proglang} 为 {IC} 编写程序的信息，请参阅link:language-guide/motoko{outfilesuffix}[_Motoko Programming Language Guide_]。

////
== 下载打包版本

[width="100%",cols=3*,"35%,30%,35%",options="header",]
|===
|Version |Tag |Documentation and supported platforms
|SDK 0.5.2 (February 2020) |sdk-0.5.2-RELEASE |Release notes / changelog
+
支持的平台

|SDK 0.5.4 (March 2020) |sdk-0.5.4-RELEASE |Release notes / changelog
+ Supported platforms
|===

== 使用软件包管理器

[source,bash]
----
npm install dfx
----

[source,bash]
----
brew install dfx
----
////