= 视频和教程
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

基础视频系列介绍了如何为互联网计算机构建应用程序。

== 以 {IC} 为基础：基础

基础视频系列介绍了如何为互联网计算机构建应用程序。
该系列由十个视频片段组成。
大多数部分的运行时间为 3 到 5 分钟，但也有更深入的技术来探索 {proglang} 编程语言、前端开发以及所有部分如何在示例应用程序中组合在一起。

++++
<h1></h1>
<br>
++++

video::jduSMHxdYD8[youtube,width=100%,height=480px]

=== {IC} 是什么，为什么要为它构建应用程序？

基础视频系列的这一部分提供了对 {IC} 的基本介绍以及它如何支持开放互联网服务的未来。

如果您想在观看视频后了解更多信息，请查看link:developers-guide/concepts/what-is-IC{outfilesuffix}[什么是互联网计算机？]。

++++
<h1></h1>
<br>
<hr>
<br>
++++

video::TXf87GTXO78[youtube,width=100%,height=480px]

=== 简化开发者体验

{IC} 通过降低生态系统复杂性使构建应用程序变得更加容易。

如果您想在观看视频后了解更多信息，请查看link:developers-guide/concepts/what-is-IC{outfilesuffix}#next-gen[构建下一代软件和服务]。

++++
<h1></h1>
<br>
<hr>
<br>
++++

video::60uHQfoA8Dk[youtube,width=100%,height=480px]

=== 什么是 DFINITY Canister SDK？

想知道什么是“容器”吗？ 不知道从哪里开始？ 该视频片段介绍了用于开发在 {IC} 上运行的程序的关键工具。

如果您已准备好开始，请访问link:下载{outfilesuffix}[下载中心]。

++++
<h1></h1>
<br>
<hr>
<br>
++++

video::yqIoiyuGYNA[youtube,width=100%,height=480px]

=== 部署你的第一个应用程序

本视频片段介绍了如何使用在本地运行的 {IC} 部署您的第一个应用程序。

要自己尝试，请按照步骤操作link:quickstart/local-quickstart{outfilesuffix}[快速入门] 教程。

++++
<h1></h1>
<br>
<hr>
<br>
++++

video::QbeP4xuPUp0[youtube,width=100%,height=480px]

=== 介绍 Motoko：为 {IC} 设计的语言

该视频片段概述了 Motoko 编程语言，并重点介绍了一些使其特别适合编写在 {IC} 上运行的应用程序的关键特性。

如果您想了解有关使用 {proglang} 的更多信息，请参阅link:language-guide/motoko{outfilesuffix}[{proglang} Programming Language] 指南。

++++
<h1></h1>
<br>
<hr>
<br>
++++

video::jWf1zY6o5xM[youtube,width=100%,height=480px]

=== 集成前端

该视频片段演示了如何使用原始 JavaScript、React 和 React 与 TypeScript 集成前端用户界面。

观看视频后，您可以自行尝试或按照link:developers-guide/tutorials/my-contacts{outfilesuffix}[添加样式表]中的步骤学习如何在使用 React 时添加样式表。

++++
<h1></h1>
<br>
<hr>
<br>
++++

video::O2KaWRtsqHg[youtube,width=100%,height=480px]

=== Candid 如何为应用程序界面提供通用语言

该视频片段描述了 Candid 如何提供通用接口描述语言 (IDL) 用于与 Internet 计算机上运行的服务进行交互。

有关 Candid 是什么以及如何使用它的更完整信息，请参阅link:candid-guide/candid-intro{outfilesuffix}[Candid] 指南或link:https://crates.io/crates/candid[Candid on crates .io]。

++++
<h1></h1>
<br>
<hr>
<br>
++++

video::UAlqO66Tweg[youtube,width=100%,height=480px]

=== 深入开发者生态系统

该视频片段重点介绍了可用于使用 {proglang} 开发程序的其他工具和资源。

要开始为社区做贡献，请查看link:https://github.com/dfinity/motoko-base[Motoko 基础库]。
++++
<h1></h1>
<br>
<hr>
<br>
++++

video::GzkRsbqPaA0[youtube,width=100%,height=480px]

=== 构建多人游戏

此视频片段展示了一个为在 {IC} 上运行而构建的多人黑白棋游戏，并展示了为 {IC} 构建应用程序所涉及的许多关键概念。

详细了解游戏是如何制作的，请参见link:https://ninegua.github.io/reversi/[在互联网计算机上构建多人黑白棋游戏]或查看源代码 link:https://github.com/ninegua/reversi[Reversi] 存储库。

++++
<h1></h1>
<br>
<hr>
<br>
++++

video::G6vUrC9lues[youtube,width=100%,height=480px]

=== 加入 {IC} 开发者社区

该视频片段总结了可用资源以及您如何参与其中。

如需更多灵感，请查看示例应用程序link:https://github.com/dfinity/examples[examples] 或link:https://github.com/dfinity/awesome-dfinity[awesome-dfinity] 存储库。
要参与对话，请加入link:https://forum.dfinity.org/[开发者论坛] 或在 Twitter 上关注link:https://twitter.com/dfinitydev[@dfinitydev]。

++++
<h1></h1>
<br>
<hr>
<br>
++++

== 教程

link:quickstart/quickstart-intro{outfilesuffix}[快速入门] 提供了对创建和部署新项目的基本工作流程的简化介绍，无需探索项目目录或示例代码的内容。

如果您想获得更多创建在 {IC} 上运行的程序的实践经验，请查看以下教程：

* link:developers-guide/tutorials/explore-templates{outfilesuffix}[Explore the default project]

* link:developers-guide/tutorials/define-an-actor{outfilesuffix}[Query using an actor]

* link:developers-guide/tutorials/hello-location{outfilesuffix}[Pass text arguments in a terminal]

* link:developers-guide/tutorials/counter-tutorial{outfilesuffix}[Increment a natural number]

* link:developers-guide/tutorials/calculator{outfilesuffix}[Use integers in calculator functions]

* link:developers-guide/tutorials/phonebook{outfilesuffix}[Import library modules]

* link:developers-guide/tutorials/multiple-actors{outfilesuffix}[Use multiple actors]

* link:developers-guide/tutorials/custom-frontend{outfilesuffix}[Customize the front-end]

* link:developers-guide/tutorials/my-contacts{outfilesuffix}[Add a stylesheet]

* link:developers-guide/tutorials/intercanister-calls{outfilesuffix}[Make inter-canister calls]

* link:developers-guide/tutorials/scalability-cancan{outfilesuffix}[Create scalable apps]

* link:developers-guide/tutorials/access-control{outfilesuffix}[Add access control with identities]
