= 去中心化数据中心
:keywords: 互联网计算机,区块链,协议,副本,子网,数据中心,智能合约,容器,开发者
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY

{IC} 不是存在于任何物理位置的物理硬件。
相反，{IC} 结合了全球独立运营的数据中心提供的计算资源。

与公共云或私有云不同，{IC} 并非由一家私营公司拥有和运营。
相反，{IC} 是一种公用事业，其更新和操作通过协议中定义的算法、去中心化治理系统进行管理。
它的架构使多台计算机能够像一个非常强大的虚拟机一样运行。

构成互联网计算机的全球数据中心中的节点被组织成子网区块链，这些子网区块链又使用链密钥加密技术相互连接。
分布式架构无需防火墙或易受攻击的技术即可实现安全通信。
独立节点运营商向数据中心支付费用以托管他们的节点，并获得报酬以提供计算能力和托管服务以支持在 {IC} 上运行的 dapp。

== 子网和数据中心

为了提供能够承受潜在服务中断的真正分散的区块链，构成任何给定区块链子网的物理节点分布在不同位置的数据中心。
节点本身可能由不同方以合作伙伴关系拥有或提供，或者与它们运营所在的数据中心位置无关。

下图提供了在四个数据中心中具有节点的子网的简化视图。

image:data-center-simplified.svg[]

在这个简化的场景中:

* 有四个地理上独立的数据中心。
* 每个数据中心都有多个节点供应商提供的硬件。
* 任何单个节点提供商都可能在多个数据中心拥有设备。

尽管此示例表示一个子网区块链，其节点位于多个数据中心，但如果需要，任何节点都可以移出该区块链子网以形成新的区块链子网。
网络拓扑的更改通过称为 **Network Nervous System** (NNS) 的 {IC} 治理系统进行管理。

== 节点提供商和数据中心运营商

在大多数情况下，节点提供商或与他们合作的数据中心运营商负责监控和维护运行 {IC} 的设备的计算能力。
例如，如果出现硬件故障或系统性能不佳，节点提供商或数据中心运营商可能需要维修或更换设备。
然而，网络运营和升级是通过分散的治理系统网络神经系统 (NNS) 进行监控和管理的。

== 想了解更多？

如果您正在寻找有关数据中心运营和节点提供商的更多信息，请查看以下相关资源:

* link:https://support.internetcomputer.org/hc/en-us/sections/4405489337748-Node-Provider[节点提供者互联网计算机帮助中心（常见问题和文章）]
