= 代币和燃料费
:keywords: 互联网计算机,区块链,ICP代币,智能合约,燃料费,钱包,软件,智能合约,容器,开发者
:proglang: Motoko
:IC: 互联网计算机
:company-id: DFINITY

在互联网计算机生态系统中，互联网计算机协议代币（ICP 代币）是一种本地实用代币，其价值在公开市场上确定。
ICP 代币在 {IC} 的治理和经济中都发挥着关键作用。

[[get-cycles]]
== 如何获得 ICP 代币

您可以通过几种不同的方式获取 ICP 代币。
例如，您可能:

* 直接通过列出可供交易的 ICP 代币的交易所购买 ICP 代币。
* 参与 {IC} 治理获得代币作为奖励
* 通过互联网计算机协会 (ICA) 或 {company-id} 基金会获得代币授予。
* 获得代币作为作为节点提供者提供计算能力的报酬。

[[using-cycles]]
== 如何使用 ICP 代币

如果您有 ICP 代币，但不确定如何使用它们，下图提供了一个简化的概述来说明三种最常见的场景。

image:icp-tokens-how-to-use.svg[]

正如该图所示，您如何使用 ICP 代币主要取决于您获取它们的目标。
例如，如果您是开发人员或企业家，则可以将 ICP 代币转换为 **cycles**。 然后可以使用周期来支付运行容器智能合约的费用，这些智能合约向市场提供产品和服务。
如果您是有兴趣参与治理和影响 {IC} 方向的社区成员，您可以将 ICP 代币锁定在一个称为神经元的权益中，以便您可以提交提案并对其进行投票。

[[how-cycles-work]]
== 燃料费如何工作

对于开发人员而言，ICP 代币很重要，因为它们可以转换为燃料费，进而用于支付资源消耗。

例如，假设您有一所房子，其中丙烷用于热水器、厨房炉灶、烘干机和空间加热器。 当您使用这些设备时，您会耗尽您手头的gas供应，因此您会定期联系供应商补充您的供应，这样您就可以继续使用您的设备而不会中断。 这类似于容器智能合约，因为每个容器都必须有一个帐户，该帐户具有可用于支付容器应用程序消耗的通信、计算和存储的周期。


[[cost-of-compute]]
== 计算成本

- 燃料费反映了托管在互联网计算机区块链中的应用程序的实际运营成本，包括物理硬件、机架空间、能源、存储设备和带宽等资源。
- 容器智能合约必须能够为完整执行（全部或全部）支付费用，但平台对容器可以持有和消耗的燃料费数设置了限制，以防止恶意代码耗尽资源。
- 运营成本的相对稳定性使得预测处理（例如，一百万条消息）所需的燃料费变得更加容易。
- 随着时间的推移，与通信、计算和存储相关的成本更有可能减少而不是增加——例如，因为磁盘空间变得更便宜，硬件更高效，{IC} 协议也将随着时间的推移而改进，以更好地利用资源。
- 燃料费不是货币；特别是燃料费不能以互联网计算机协议代币的形式转换回价值，但可以在容器之间转移以使容器能够支付运营费用。


[[volatility]]
== 代币价值和波动性


- 代币反映 {IC} 区块链的价值并且可以波动。 为了防止令牌值影响容器可以处理的消息数量，令牌不用于直接支付资源。
- 代币可以在代币持有者之间交换或锁定在**神经元**中，以确保作为治理系统一部分的投票权。
- 代币用于奖励提供计算能力的节点提供者和通过投票和提交提案参与{IC}治理的神经元持有者。


[[data-centers]]
== 向节点提供者付款


借助该模型，互联网计算机区块链为节点提供商提供了一个可预测的计算能力经济模型，以确保资源在需要的时间和地点可用。 节点提供者获得活动和备用节点的补偿，以便互联网计算机区块链有能力处理正常流量和工作负载峰值。

互联网计算机经济模型将管理容量的大部分权力和责任置于治理系统——网络神经系统上。 有关薪酬和服务水平要求的具体细节不在本文档的范围内。

== 想了解更多？

如果您正在寻找有关令牌和周期的更多信息，请查看以下相关资源:

* link:https://www.youtube.com/watch?v=H2p5q0PR2pc[通证经济学概述（视频）]