= 黑客松项目
:描述: dapp 常见用例示例代码的快速链接
:关键词: 互联网计算机,区块链,加密货币,ICP代币,智能合约,燃气费,钱包,软件容器,开发者入职,dapp,例子,代码,rust,Motoko
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

来自世界各地的开发者正在参加黑客松，在IC上构建dapp、工具和其他类型的项目。来找找灵感，并查看一些获奖项目的源代码。

[[dfinihack]]
== DFINIHack

黑客松是一种很好的学习方式，这就是为什么除了外部黑客松之外，我们还在 DFINITY 举办内部黑客松。 来自所有部门的每个人都可以参与，无论是否有编码经验。 目标是探索新的用例，评估我们为开发人员提供的文档和工具，并在内部推广开发者文化。 

=== Sidekick
Sidekick 是一个运行在互联网计算机上的 dapp，它可以从几行代码构建容器智能合约。

- https://github.com/blynn/sidekick[See code on GitHub]
- https://ffgig-jyaaa-aaaae-aaaoa-cai.raw.ic0.app[Live Canister]

=== IC Vault
IC Vault 通过端到端加密确保通过互联网计算机在设备之间安全同步数据（即，互联网计算机看不到任何明文）。

- https://github.com/timohanke/hack13[See code on GitHub]
- https://xggrc-cyaaa-aaaaj-aaasq-cai.raw.ic0.app[Live Canister]
- https://youtu.be/16xxA8EKEhE[Presentation on YouTube]

=== PrivIC
PrivIC (pronounced “privacy”) provides identity management on the Internet Computer. Users can visit the PrivIC app directly to manage their identity, which consists of attributes such as name, date of birth, email, and phone number, or do so as part of the register/sign-in flow from an app.

- https://github.com/open-ic/priv-ic[See code on GitHub]

=== DeFind
DeFind 是一个基于质押的搜索引擎。 在今天的互联网上，搜索引擎使用网络爬虫将数据输入秘密算法。 对于广告商来说，这会产生错误的激励——例如，他们可能会被激励用不可见的文本来欺骗网络爬虫，或者通过机器人产生虚假流量。

- https://github.com/IC-Search/ic-search[See code on GitHub]
- https://jbioa-siaaa-aaaai-qanfq-cai.ic0.app[Live Canister]

=== IC Notary
IC Notary 是一种带有时间戳的公证服务，允许用户证明他们在某个时间点持有文档（或任意文件）。 用户可以上传文件到IC Notary，也可以搜索和下载之前上传的文件。

- https://github.com/jplevyak/dfnhack7[See code on GitHub]
- https://jbxh5-eqaaa-aaaae-qaaoq-cai.ic0.app[Live Canister]

=== IC Netboot
IC Netboot 允许开发人员直接从容器引导虚拟机 (VM)，从而使引导基础设施分散且不可阻挡。 此外，它还可以作为 zookeeper 等应用程序的 VM 数据故障转移。 最后，这是通过 TFTP/DHCP/iPXE 等合法协议与互联网计算机通信的概念证明。

- https://github.com/farazshaikh/team14[See code on GitHub]





