= {release} 中的新功能亮点
:描述: DFINITY容器软件开发套件发行说明
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY
:release: 0.6.26
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

{release} 版本主要包含支持尚未完成的新功能的更改，包括对 DFX 命令、{proglang}、{proglang} 基础库和 Candid 的修复和更新。

== 新特性和功能

此版本中包含的最重要的新功能是发布 link:../interface-spec/index{outfilesuffix}[_{IC} 接口规范_]。

_{IC} 接口规范_ 详细描述了许多描述与 {IC} 交互的低级接口的技术属性。
例如，_{IC} 接口规范_ 描述了为处理传入请求而公开的 HTTPS 端点，以及低级绑定如何使容器能够与系统组件交互。

如果您使用现有工具（如 DFINITY Canister SDK 或 Canister Development Kit for Rust）来处理容器，这些工具会代表您与_{IC}接口规范_中描述的低级接口交互。
但是，如果您想创建自己的工具来处理容器，_{IC} 接口规范_ 包含您需要了解 {IC} 外部接口如何工作的技术细节。

如果您对扩展 {IC} 生态系统感兴趣，您还可以在_{IC} 接口规范_ 中找到信息，以帮助您开发以下类型的项目:

* 为任何编程语言（包括 Python、Golang 或 C 等流行语言）构建*前端代理*以进行面向用户的交互。
* 以任何可以编译为 WebAssembly 字节码的语言构建*后端容器开发工具包*（CDK）。
* 构建*本地开发工具*，例如命令行界面或 Internet 计算机仿真器和调试器。
* 实施*功能和增强*以改善开发人员部署和管理在网络上远程运行的容器的体验。

== 此版本中修复的问题

本节涵盖了已在此版本中修复的所有报告的问题。

此版本修复了默认循环钱包中的内存分配问题，该问题在创建和部署容器后导致错误。
如果您遇到此问题，您可能会看到类似于以下内容的错误消息:

……
副本返回错误:代码 5，消息:“容器 6dtaa-vaaaa-aaaab-aaipa-cai 超出其允许的内存分配”
……

此版本更新了默认燃料费钱包，以更好地处理未使用的内存以及在创建和部署容器时如何分配内存。

== 已知问题和限制

本节涵盖可能影响您在特定环境或场景中使用 {sdk-short-name} 的任何已知问题或限制。

=== 只有默认的钱包容器主体可以执行容器管理任务

燃料费钱包容器的引入改变了用于执行关键容器管理任务的默认主体，例如注册新容器标识符和在 {IC} 上部署新容器。
此更改在用于执行某些任务的身份中引入了一些不一致，并可能导致潜在的访问控制问题。

您应该注意，尚未更新任何教程以反映这种特定的行为变化以及当前版本link:../developers-guide/tutorials/access-control{outfilesuffix}[使用身份添加访问控制] 教程 已知对于此版本无效。
如果您想尝试访问控制 link:../developers-guide/tutorials/access-control{outfilesuffix}[使用身份添加访问控制] 教程，您应该安装 {sdk-short-name} 版本 0.6.23（或更早版本）。

=== 在项目中直接使用 JavaScript 代理时不兼容

如果您直接在项目中访问 `@dfinity/agent` JavaScript 代理（即不通过引导服务器），您将无法使用 `agent-js` 版本导入 `bls` 认证方案。

如果您的应用程序直接使用 JavaScript 代理，您应该使用最新版本的代理。