= {release} 中的新功能亮点
:描述: DFINITY容器软件开发套件发行说明
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY
:release: 0.6.22
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

{release} 版本包含支持尚未完成的新功能的更改，包括对 DFX 命令、{proglang}、{proglang} 基础库和 Candid 的修复和更新。

== 新特性和功能

最重要的新特性和功能包括以下功能领域的更新：

* <<DFX,DFX>>
* <<Apps,Sample applications>>
* <<Candid,Candid>>
* <<Motoko,Motoko>>

=== DFX

* 当需要但未提供参数时，`+dfx canister call+` 命令现在可以将随机生成的值传递给容器方法。

* `+dfx canister call+` 命令可以获取本地容器的容器标识符，即使容器安装在远程网络上也是如此。

* `+dfx replica+` 命令已修复，因此它不会尝试将副本 `+pid+` 写入不存在的目录。

* 创建新项目时使用的默认 `+webpack.config.js+` 文件已被修改为注释掉配置以启用 TypeScript。
+
之前，`+webpack.config.js+` 文件配置 `+ts-loader+` 来处理带有 `+.js+` 文件扩展名的文件，这可能会导致错误。
现在默认禁用此配置，注释掉的配置仅通过 `ts-loader` 处理 `.ts`、`.tsx` 和 `.jsx` 文件。

[[Apps]]
=== 示例应用程序

* 已添加了更新、改进和新的示例应用程序 link:https://github.com/dfinity/examples/tree/master/motoko[example] 存储库。
+
所有 Motoko 示例应用程序： link:https://github.com/dfinity/examples/tree/master/motoko[example] 存储库已更新，可与 {sdk-short-name} 的最新版本一起使用。
+
还有新的示例应用程序来说明使用数组 (link:https://github.com/dfinity/examples/tree/master/motoko/quicksort[Quicksort]) 和构建创建/读取/更新/删除 (CRUD) 操作 一个网页应用 link:https://github.com/dfinity/examples/tree/master/motoko/superheroes[Superheroes].

* The link:https://github.com/dfinity/linkedup[LinkedUp] 示例应用程序已更新，可与最新版本的 Motoko 和 SDK 配合使用。

=== Candid

* link:https://github.com/dfinity/candid/blob/master/Changelog.md[Candid changelog]

=== Motoko

* Motoko 编译器现在报告带有附加错误代码的错误和警告。
+
您可以通过将带有代码的 `+--explain+` 标志传递给编译器，使用错误代码来查找给定错误的更详细描述。
+
请注意，大多数错误代码的详细描述尚不可用，并将在即将发布的版本中逐步添加。
////
== 此版本中修复的问题

本节涵盖了已在此版本中修复的所有报告的问题。

== 已知问题和限制

本节涵盖可能影响您在特定环境或场景中使用 {sdk-short-name} 的任何已知问题或限制。
////