= {release} 中的新功能亮点
:描述: DFINITY容器软件开发套件发行说明
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY
:release: 0.8.4
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

{release} 版本概述:

* 添加了对 Rust容器的一流支持。
* 包含的副本现在支持 canister_heartbeat。

== 对 DFX 的更改

=== 新功能:添加了“Rust”容器类型

您现在可以在 dfx.json 中声明“Rust”容器。
[source, json]
----
{
  "canisters": {
    "canister_name": {
      "type": "rust",
      "package": "crate_name",
      "candid": "path/to/canister_name.did"
    }
  }
}
----

不要忘记在项目根目录中放置一个`Cargo.toml`。
然后 dfx 将使用您的 rust 工具链构建 rust 容器。 还请确保您已添加 WebAssembly 编译目标。

[source, bash]
----
rustup target add wasm32-unknown-unknown
----

还可以使用默认的 rust 容器创建新的 dfx 项目。

[source, bash]
----
dfx new --type=rust <project-name>
----

311 / 5,000
翻译结果
=== 更新了新的项目模板

将 Webpack 的依赖项更新为最新的，并更新了配置。 另外简化了配置中容器 ID 的环境变量。

此外，还为入门模板添加了一些润色，包括网站图标并在示例应用程序中使用更多语义 html 

=== 新功能:可执行路径名的环境变量覆盖

您现在可以通过指定环境变量来覆盖通常从缓存中调用的任何可执行文件的位置。 例如，DFX_ICX_PROXY_PATH 将指定 `icx-proxy` 的路径。

=== 新功能:dfx deploy --mode=reinstall <canister>

`dfx deploy` 现在可以重新安装单个容器，由新的 `--mode=reinstall` 参数控制。
这是破坏性的（它会重置容器的状态），因此需要确认并且一次只能在一个容器上执行。

`dfx canister install --mode=reinstall <canister>` 也需要相同的确认，并且不再适用于 `--all`。

== 对副本的更改

包含的副本现在支持 canister_heartbeat。 这暂时只适用于Rust 容器，不适用于模拟器（`dfx start --emulator`）。
