= Developer Release Notes
:description: DFINITY Canister Software Development Kit Release Notes
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY
:release: 0.8.4
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

{sdk-long-name} 使开发人员能够开发在 {IC} 上运行的应用程序。
{proglang} 新编程语言与 {sdk-long-name} 捆绑在一起，为创建防篡改软件和开放互联网服务提供原生支持。

{sdk-short-name} 提供了执行以下关键任务所需的一切:

- 在 {proglang} 中编写容器并将它们编译为 WebAssembly。
- 模拟在您的开发计算机上本地运行的 {IC} 网络。
- 将编译后的程序部署为link:../developers-guide/glossary{outfilesuffix}#g-canister[canisters]。
- 使用命令行界面或通过 Web 浏览器与您的应用程序服务交互。

[NOTE]
=====================================================================
当前版本的 {sdk-long-name} 旨在向您介绍构建在 {IC} 上运行的应用程序，并提供对 {IC} 网络的访问以进行应用程序测试、演示和探索。
{sdk-long-name} 目前不应用于开发_生产应用程序_。
=====================================================================

== 已知问题和限制

本节涵盖可能影响您在特定环境或场景中使用 {sdk-short-name} 的任何已知问题或限制。

* 创建新项目会显示错误或警告。
+
默认情况下，创建新项目会安装节点依赖项以支持为您的项目构建前端。
+
根据您的环境，节点依赖项的安装可能会显示由 `+npm+` 包管理器生成的错误或警告。
+
`+npm+` 包管理器发出的错误和警告不会阻止您成功创建新项目，并且在大多数情况下，可以放心地忽略。

== 其他问题和反馈

加入link:https://forum.dfinity.org/[DFINITY 开发者论坛] 是向社区成员学习、提出问题、寻求其他开发者帮助以及提供有关您的体验的见解和反馈的有效方式。

如果您有社区未回答的问题，您可能还想查看link:../developers-guide/troubleshooting{outfilesuffix}[Troubleshooting] 主题以获取有关常见问题、已知问题的解决方法或帮助的信息 排除警告或错误。

如需技术支持，请发送电子邮件至 support@dfinity.org[DFINITY支持]。

知识库文章的自助帮助中心也即将推出。
