= 使用多个actor
February 2020 (Alpha)
ifdef::env-github,env-browser[:outfilesuffix:.adoc]
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY

在本教程中，您将创建一个包含多个参与者的项目。
目前，您只能在 {proglang} 文件中定义一个参与者，并且一个参与者总是被编译到一个容器中。
此外，您还不能从另一个容器中定义的actor调用一个容器中的actor中定义的函数，或者定义一个actor类来支持您的{proglang}程序中的多个actor实例。
但是，您可以创建具有多个参与者的**项目**，并且可以从同一个 `+dfx.json+` 配置文件构建多个容器。

在本教程中，您将为同一项目中的三个actor创建单独的程序文件。
该项目定义了以下不相关的参与者:

* `+assistant+`actor 提供了在待办事项列表中添加和显示任务的功能。
+
为简单起见，本教程的代码示例仅包含添加待办事项和显示已添加的待办事项列表的功能。该程序的更完整版本（具有将项目标记为完整和从列表中删除项目的附加功能）包含在链接中link:../sample-apps{outfilesuffix}[示例代码、应用程序和微服务]。

* `+factorial+`actor 提供了一个函数来确定指定数字的阶乘。

* `+daemon+` 角色提供了启动和停止守护进程的模拟函数。
+
此代码示例仅分配一个变量并打印消息以用于演示目的。

== 开始之前

在开始本教程之前，请验证以下内容:

* 您已按照中所述下载并安装了 SDK
link:../getting-started{outfilesuffix}[开始]。
* 您已停止在本地运行的任何网络副本进程
计算机。

完成本教程大约需要 20 分钟。

== 创建一个新项目

要为本教程创建一个新项目:

[arabic]
. 如果您还没有打开一个终端外壳，请在您的本地计算机上打开一个终端外壳。
. 更改为您用于 {IC} 项目的文件夹（如果您正在使用一个）。
. 通过运行以下命令创建一个新项目:
+
[source,bash]
----
dfx new multiple_actors
----
. Change to your project directory by running the following command:
+
[source,bash]
----
cd multiple_actors
----

== 修改默认配置

您已经看到创建一个新项目会在您的项目目录中添加一个默认的 `+dfx.json+` 配置文件。
对于本教程，您需要在此文件中添加部分以指定每个程序的位置，这些程序定义了您要构建的参与者。

修改默认的 `+dfx.json+` 配置文件:

. 在文本编辑器中打开 `+dfx.json+` 配置文件，然后将默认的 `+multiple_actors+` 容器名称和源目录更改为 `+assistant+`。
+
例如:
+
[source,bash,subs="quotes"]
----
{
  "canisters": {
    "*assistant*": {
      "frontend": {
        "entrypoint": "src/multiple_actors/public/index.js"
      },
      "main": "src/*assistant*/main.mo"
    },
----
+
因为您要向配置文件的这个 `+canisters+` 部分添加设置，所以还必须在包含 `+assistant+` 主源代码文件位置的大括号之后添加一个**逗号**。
. 为 `+factorial+` 程序添加新的容器名称和源文件位置，并在 `+assistant+` 源文件位置下方为 `+daemon+` 程序文件添加新的容器名称和源文件位置。
+
例如:
+
[source,bash,subs="quotes"]
----
    "factorial": {
      "main": "src/factorial/main.mo"
    },
    "daemon": {
      "main": "src/daemon/main.mo"
        }
  },
----
+
您可以按原样保留其他部分。
. 通过运行以下命令，更改默认源文件目录的名称以匹配 `+dfx.json+` 配置文件中指定的名称:
+
[source,bash]
----
cp -r src/multiple_actors/ src/assistant/
----
. 复制`+assistant+`源文件目录，通过运行以下命令为`+factorial+`actor创建主程序文件:
+
[source,bash]
----
cp -r src/assistant/ src/factorial/
----
. 复制 `+assistant+` 源文件目录，通过运行以下命令为 `+daemon+` actor 创建主程序文件:
+
[source,bash]
----
cp -r src/assistant/ src/daemon/
----

== 修改默认模板程序

现在，`+src+` 目录中有三个单独的目录，每个目录都有一个模板 `+main.mo+` 文件。
在本教程中，您将用不同的 actor 替换每个模板 `+main.mo+` 文件中的内容。

修改默认模板源代码:

. 在文本编辑器中打开 `+src/assistant/main.mo+` 文件并删除现有内容。
. 将以下示例代码复制并粘贴到文件中:
+
[source.copy,motoko,no-repl]
----
include::example$multiple-actors/assistant/main.mo
----
. 在文本编辑器中打开 `+src/factorial/main.mo+` 文件并删除现有内容。
. 将以下示例代码复制并粘贴到文件中:
+
[source.copy,motoko,no-repl]
----
include::example$multiple-actors/factorial/main.mo
----
. 在文本编辑器中打开 `+src/daemon/main.mo+` 文件并删除现有内容。
. 将以下示例代码复制并粘贴到文件中:
+
[source.copy,motoko,no-repl]
----
include::example$multiple-actors/daemon/main.mo
----

== 构建项目中的所有容器

您现在有一个程序，您可以将其编译成可执行的 WebAssembly 模块，您可以将其部署在本地副本网络上。

为项目中的每个参与者构建可执行文件:

. 如果需要，切换到项目的 `+~/ic-projects/multiple_actors+` 根目录。
. 通过运行以下命令为每个程序构建 WebAssembly 可执行文件:
+
[source,bash]
----
dfx build --all
----
+
如果命令成功，它将构建您在 `+dfx.json+` 文件中指定的所有容器。
+
[source,bash]
----
Building canister assistant
Building canister factorial
Building canister daemon
----

== 在项目中部署容器

您现在拥有三个独立的编译程序——每个参与者一个程序——准备好进行部署。

要部署容器:

. 通过运行以下命令在本地计算机上启动 {IC} 网络:
+
[source,bash]
----
dfx start
----
. 打开一个新的终端 shell，然后为您的项目更改 `+~/ic-projects/multiple_actors+` 根目录。
+
例如:
+
[source,bash]
----
cd ~/ic-projects/multiple_actors
----
. 通过运行以下命令在本地网络上部署您的容器:
+
[source,bash]
----
dfx canister install --all
----

== 通过调用函数验证部署

您现在在本地副本网络上部署了三个程序作为 *canisters*，并且可以使用 `+dfx canister call+` 命令测试每个程序。

要测试您在本地副本网络上部署的程序:

. 使用 `+dfx canister call+` 命令通过 `+addTodo+` 函数调用容器 `+assistant+`，并通过运行以下命令将要添加的任务传递给它:
+
[source,bash]
----
dfx canister call assistant addTodo '("Schedule monthly demos")'
----
. 通过运行以下命令，验证该命令是否使用 `+showTodos+` 函数返回待办事项列表项:
+
[source,bash,subs="quotes"]
----
dfx canister call assistant showTodos
----
+
The command returns output similar to the following:
+
[source,bash]
----
("
___TO-DOs___
(1) Schedule monthly demos
----
. Use the `+dfx canister call+` command to call the canister `+factorial+` using the `+fac+` function by running the following command:
+
[source,bash,subs="quotes"]
----
dfx canister call factorial fac '(8)'
----
+
The command returns the result of the function:
+
[source,bash]
----
(40320)
----
. Use the `+dfx canister call+` command to call the canister `+daemon+` using the `+launch+` function by running the following command:
+
[source,bash]
----
dfx canister call daemon launch
----
. Verify the mock `+launch+` function returns "The daemon process is running" message":
+
[source,bash]
----
(""The daemon process is running"")
----
. Stop the {IC} processes running on your local computer by running the following command:
+
[source,bash]
----
dfx stop
----

////
== 导入actor

要扩展您在本教程中学到的知识，您可能需要尝试修改源代码以返回不同的结果。
 
随着功能的添加，可以修改教程以说明其他功能，例如:
- 如何导入actor
- 如何在另一个actor中调用函数
- 如何在一个节目中包含多个actor
- 如何以及何时添加actor类

////
