[[candid-ui]]
== 在浏览器中测试功能


容器接口描述语言（通常称为 Candid 或更一般地称为 IDL）为指定容器智能合约的签名提供了一种通用语言。
Candid 为您提供了一种统一的方式来与用不同语言编写或使用不同工具访问的容器智能合约进行交互。
例如，无论底层程序是原生 Rust、JavaScript 还是 {proglang}，Candid 都能提供一致的服务视图。
Candid 还启用了不同的工具——例如`+dfx+` 命令行界面和网络神经系统 dapp——来共享服务的通用描述。

基于 actor 的类型签名，Candid 还提供了一个 Web 界面，允许您调用容器函数进行测试和调试。


使用 `+dfx deploy+` 或 `+dfx canister install+` 命令在本地容器执行环境中部署项目后，您可以在浏览器中访问 Candid Web 界面端点。
此 Web 界面 — Candid UI — 以表单形式公开服务描述，使您无需编写任何前端代码即可快速查看和测试功能并尝试输入不同的数据类型。

要使用 Candid Web 界面测试容器功能:

.使用 `+dfx canister id __Candid_UI+` 命令查找与当前项目关联的 Candid UI 容器标识符。
+
[source,bash]
----
dfx canister id __Candid_UI
----
+
该命令显示 Candid UI 的容器标识符，输出类似于以下内容:
+
....
r7inp-6aaaa-aaaaa-aaabq-cai
....
+
. 复制 Candid UI 容器标识符，使其在剪贴板中可用。
. 如果您已停止本地容器执行环境，请通过运行以下命令在本地重新启动它:
+
[source,bash]
----
dfx start --background
----
. 打开浏览器并导航到 `+dfx.json+` 配置文件中指定的地址和端口号。
+
默认情况下，本地容器执行环境绑定到`+127.0.0.1:8000+`地址和端口号。
. 将所需的 `+canisterId+` 参数和 `+dfx canister id __Candid_UI+` 命令返回的 Candid UI 容器标识符添加到 URL。
+
例如，完整的 URL 应该类似于以下内容，但带有由 `+dfx canister id __Candid_UI+` 命令返回的`+CANDID-UI-CANISTER-IDENTIFIER+`:
+
....
http://127.0.0.1:8000/?canisterId=<CANDID-UI-CANISTER-IDENTIFIER>
....
+
例如，对于 Candid UI 的示例容器标识符，如上所示，可能如下所示:
+
....
http://127.0.0.1:8000/?canisterId=r7inp-6aaaa-aaaaa-aaabq-cai
....
+
然后，浏览器会显示一个表单供您指定容器标识符或选择 Candid 描述 (`+.did+`) 文件。
请注意，此字段是指您要与之交互的容器的容器标识符（与我们在上一步中使用的 Candid UI 的容器标识符相反）。
+
. 在 *Provide a canister ID* 字段中指定要测试的容器的容器标识符，然后单击 *Go* 以显示服务描述。
+
如果您不确定要使用哪个容器标识符，可以运行 `+dfx canister id+` 命令来查找特定容器名称的标识符。
例如，要获取名为 `+my_counter+` 的容器的容器标识符，您可以使用:
+
....
dfx canister id my_counter
....
+
. 查看 dapp 中定义的函数调用和类型列表。
. 为函数键入适当类型的值或单击 *Random* 生成值，然后单击 *Call* 或 *Query* 以查看结果。
+
请注意，根据数据类型，Candid 界面可能会显示用于测试功能的其他配置设置。
例如，如果一个函数接受一个数组，您可能需要在输入值之前指定数组中的项目数。
