= 新手的初步步骤
:commandkey: &#8984;
:sdk-short-name: DFINITY Canister SDK

如果这是您第一次在计算机上安装开发人员工具，您可能需要采取一些额外的步骤来准备您的环境。

但是，通常有多种方法可以执行这些任务中的每一个。
如果您需要比此处提供的更多帮助，请参阅您正在使用的操作系统的文档。

注意：此处的说明假设您使用的是 macOS 计算机。
如果您有 Linux 开发环境，则要遵循的步骤取决于您使用的特定 Linux 发行版和版本。

在安装 {sdk-short-name} 之前，您需要了解：

* 如何在终端中打开和运行命令
* 如何检查和安装包和依赖项
* 如何创建和导航到新目录
* 如何在您使用的平台上查看和更新您的 PATH

本节中的步骤描述了如何准备基本的开发环境。

[[open-terminal]]
== 打开终端

您需要知道如何打开终端并导航到目录以安装 {sdk-short-name} 并在尝试任何启动和停止在本地运行的 {IC}link：../developers-guide/tutorials- 介绍{outfilesuffix}[教程]。

在 macOS 上打开终端应用程序：

. 打开查找器。
. 单击 *Applications*，打开 *Utilities*，然后双击 *Terminal*。
+
或者，您可以按 kbd:[{commandkey} + 空格键] 键盘键打开搜索，然后键入“终端”。
+
终端是您要执行命令行指令的地方。
要执行命令，请键入或复制并粘贴指令，然后按 kbd:[Return]。
. 通过运行打印工作目录-`pwd`-命令检查当前路径，然后按 kbd:[Return]。
+
[source,bash]
----
pwd
----
+
此命令显示您当前的目录，其路径类似于 `/Users/<your-user-name>`。
+
打开终端应用程序后，您可以通过单击*Shell*，然后选择*New Window* 或*New Tab*，随时打开新的终端shell。
+
默认情况下，一个新的终端 shell 总是在你的主目录中打开，路径类似于 `/Users/<your-user-name>`。

[[check-pkgs]]
== 检查软件包

Homebrew 应用程序是 macOS 的软件包管理器，它可以轻松安装和更新软件包（即外部程序），您需要在本地开发环境中提供这些软件包。

`node.js` 包为前端用户界面开发提供了 JavaScript 运行时环境和模块。
`node.js` 包不是构建程序所必需的，但如果你想为你的程序添加一个图形用户界面，你可能需要它。

注意：如果您的开发环境是 Linux，您可以使用您选择的包管理器而不是 Homebrew 来安装软件包和管理依赖项。

检查和安装软件包：

. 通过运行以下命令检查您是否安装了 Homebrew 软件包管理器：
+
[source,bash]
----
brew --version
----
+
如果命令返回版本信息，继续下一步。
如果未安装 Homebrew，请将以下命令复制并粘贴到终端中：
+
[source,bash]
----
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
----
. 通过运行以下命令检查您是否安装了 `node.js` 包管理器：
+
[source,bash]
----
node --version
----
+
我们支持的node.js的最低版本是12。如果命令返回版本信息并且你的node版本至少是12，继续<<创建工作文件夹>>。
如果 `node.js` 未安装，或者您的安装已过期，请将以下命令复制并粘贴到终端中：
+
[source,bash]
----
brew install node@16
----

[[working-folder]]
== 创建一个工作文件夹

默认情况下，一个新的终端 shell 总是在你的主目录中打开，路径类似于 `/Users/<your-user-name>`。
为了让您的工作空间保持整洁，您可以为您的 {IC} 项目创建一个单独的文件夹。

为 {IC} 项目创建工作文件夹是可选的，但可以更轻松地在项目之间查找和导航。
如果您计划尝试使用以下任何link:../developers-guide/tutorials-intro{outfilesuffix}[tutorials]，则单独的文件夹特别有用：quickstart-intro{outfilesuffix}[快速开始]。

要创建一个新的工作文件夹：

. 如果您还没有打开一个终端外壳，请在您的本地计算机上打开一个终端外壳。
. 通过运行以下命令在您的主目录中创建一个名为 `+ic-projects+` 的新文件夹：
+
[source,bash]
----
mkdir ic-projects
----
. 通过运行以下命令切换到新的工作文件夹：
+
[source,bash]
----
cd ic-projects
----

[[check-path]]
== 查看 PATH 中的目录

`+PATH+` 环境变量是操作系统用来定位的重要设置
可执行程序所在的目录集。
因为每个操作系统都有自己的一组希望找到程序的目录，所以您需要知道如何查看和更新​​ PATH 环境变量，以便您可以验证 {sdk-short-name} 命令行可执行文件——` +dfx+`—位于列出的目录之一中。

在 macOS 计算机上，`+dfx+` 可执行文件的默认位置是 `+/usr/local/bin+`，并且此目录通常包含在默认路径集中。
因此，运行 macOS 的计算机通常不需要更新 `+PATH+` 变量。
但是，如果您使用的是 Linux 发行版，您应该知道如何执行以下操作：

* 验证 `+dfx+` 可执行文件的位置。
* 查看当前 `+PATH+` 中的目录集。
* 如有必要，更新 `+PATH+` 环境变量。

在大多数操作系统上，您可以运行类似于以下的命令来查看当前 `+PATH+` 中的目录集：

....
export $PATH
....

要在安装 {sdk-short-name} 后检查 `+dfx+` 可执行文件的位置，可以运行类似于以下的命令：

....
which dfx
....

如果 `+dfx+` 可执行文件不在当前 `+$PATH+` 中列出的目录之一，则需要移动可执行文件或更新 `+PATH+` 设置。
更新 `+PATH+` 的具体步骤取决于您的操作系统，但在许多情况下，您可以运行类似于以下的命令并指定适当的目录，例如 `+~/bin+`：

....
export PATH="<path-to-directory-for-dfx>:$PATH"
....

现在您已准备好link:local-quickstart{outfilesuffix}#download-and-install[install] {sdk-short-name} 并开始编程！
