= 介绍互联网计算机
:描述: 在互联网计算机上开始编程。找到文档、演练和教程，开始构建去中心化的应用程序、DeFi和基于区块链的新颖服务
:关键词: 互联网计算机,区块链,加密货币,ICP代币,智能合约,燃料费,钱包,软件容器,开发人员入职
:proglang: Motoko
:IC: Internet Computer
:公司-id: DFINITY
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

大家好!

如果你登陆到这里，有兴趣了解更多关于互联网计算机的信息。那么你来对了地方--看看下面的内容，看看从哪里开始吧！

注释: 合格的开发者可以获得价值20美元的免费燃料费，开始向互联网计算机区块链部署容器智能合约。link:https://faucet.dfinity.org/auth[申请你的免费燃料费]

[[for-first-timers]]
== 针对: 新手
互联网计算机是一个以网络速度运行的区块链，容量不受限制。

作为区块链历史的速成课程，比特币创造了数字黄金。然后，在下一步的演变中，以太坊开发了智能合约并开创了DeFi和NFT用例。

互联网计算机是第三大区块链创新--区块链可以扩展智能合约的计算，以网络速度运行它们，有效地处理和存储数据，并为开发者提供强大的软件框架。通过使之成为可能，互联网计算机使系统和应用程序的运行方式得到了完全的重新想象。

有兴趣了解更多吗？请查看以下资源：

* link:https://www.youtube.com/watch?v=YWHTNr8RZHg&list=PLuhDt1vhGcrf4DgKZecU3ar_RA1cB0vUT&index=17&ab_channel=DFINITY[互联网计算机入门]， 10分钟的互联网计算机高级概述
* link:https://medium.com/dfinity[互联网计算机博客]， 我们的博客涵盖了互联网计算机的更新
* link:https://thereboot.com/[thereboot], 我们的探讨当前互联网的问题的技术性出版物

在官方上关注我们获取最新的更新信息link:https://twitter.com/dfinity[DFINITY Twitter]。


[[for-developers]]
== 针对: 开发者
互联网计算机承载着特殊的智能合约，称为 link:https://medium.com/dfinity/software-canisters-an-evolution-of-smart-contracts-internet-computer-f1f92f1bfffb[canisters]. 容器智能合约是一些 link:https://webassembly.org/[WebAssembly]字节码逻辑和内存页。互联网计算机上的Dapps是由一个或多个容器创建的。

容器智能合约可以直接向终端用户提供网络内容，例如在他们的浏览器中，用户可以与区块链服务互动，而无需持有代币。

互联网计算机区块链最终可以承载任何数量的容器智能合约（即代码和状态）。此外，它可以以无限制的链上容量并发运行它们。这意味着你可以创建可以扩展的dapp。

容器智能合约是不可阻挡和不可篡改的。想象一下，建设时不必担心数据库、缓存、防火墙、CDN、云供应商、VPN、DNS，甚至用户名和密码--所有这些都是因为互联网计算机将这些需求抽象出来了。

跃跃欲试了吗？看看我们的 xref:quickstart:quickstart-intro.adoc[快速入门]，开始使用一个简单的hello world dapp。

对融入我们的开发者社区感兴趣吗？请查看以下内容：

* link:https://discord.gg/cA7y6ezyE2[Developer Discord]， 我们为开发者社区提供的官方 Discord
* link:https://forum.dfinity.org/[开发者论坛]， 一个关于在互联网上建立计算机的技术讨论的温馨空间。

您可以通过link:https://twitter.com/dfinitydev[DFINITY Developer Twitter] 关注我们，了解最新的开发者更新。


[[for-protocol-enthusiasts]]
== 针对: 协议爱好者

互联网计算机是由互联网计算机协议（"ICP"）创建的，它已经形成了世界上第一个网络速度、网络服务的公共区块链。互联网计算机是自我管理的，可以根据需要增长其容量。它结合了由世界各地的独立数据中心集体运行的特殊节点机器。像所有区块链一样，它是不可阻挡的，它所存储的代码是不可篡改的。

从我们左边的 "概念 "部分开始，从 xref:developers-guide:concepts/what-is-IC.adoc[什么是互联网计算机]

要了解更多关于互联网计算机协议的信息，请查看以下资源：

* link:https://dfinity.org/technicals/[技术库], 了解我们世界级研发团队解释互联网计算机协议组成部分的深入视频。特别值得注意的是:
** link:https://dfinity.org/technicals/chain-key-technology[chain-key技术], 是使互联网计算机能够扩展到数百万节点的基本突破之一。链式钥匙加密法最显著的创新是，互联网计算机有一个单一的公钥，这使得任何设备都可以验证互联网计算机产生的人工制品的真实性，甚至是智能手表和手机。
* xref:interface-spec:index.adoc[接口规范], 是一份深入的技术文件，提供了互联网计算机的低级外部接口的概述
* link:https://dashboard.internetcomputer.org/[互联网计算机仪表盘], 以监测围绕互联网计算机区块链的实时指标。
