= 选择数字资产自托管
:IC: Internet Computer
:company-id: DFINITY
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

自托管是一种代币分发选项，使您能够对自己的数字资产和私钥的管理负全部责任，而无需第三方代表您行事。

如果您选择自己控制您的数字资产，您应该知道有不同类型的*自我托管解决方案*，并且这些解决方案的安全性和易用性各不相同。
在决定特定的自托管解决方案之前，您应该花一些时间了解可用的各种选项以及它们之间的区别。

本指南简要介绍了作为您保管策略的一部分的 *冷存储* 的概念以及目前可用的最常见的冷存储类型。

有关冷存储和其他保管选项的更多信息，您应该自己研究，并确保在彻底了解各种选项后再做选择。

== 冷存储

冷存储意味着您将私钥离线存储在未连接到互联网的设备中。
冷存储是一种流行的数字资产自我保管解决方案，即使存在软件安全漏洞或冷存储解决方案丢失或被盗，您的密钥也很难被泄露。

有关冷存储方法和保护私钥的最佳实践的更多信息，请参阅以下附加资源：

* link:https://www.investopedia.com/terms/c/cold-storage.asp[冷存储]

* link:https://www.ledger.com/academy/hardwarewallet/best-practices-when-using-a-hardware-wallet#:~:text=%E2%80%93%20Keep%20your%20Recovery%20sheet%20physically,or%20smartphone%20screen%20with%20caution[使用硬件钱包时的最佳实践]

* link:https://blog.trailofbits.com/2018/11/27/10-rules-for-the-secure-use-of-cryptocurrency-hardware-wallets/[加密货币硬件钱包安全使用10条规则 ]

== 常见的冷存储选项

最常见的冷存储类型包括：

* <<硬件钱包>>
* <<气隙计算机>>
* <<纸钱包>>

=== 硬件钱包

*硬件钱包*是保存您的数字资产的物理设备。
私钥存储在设备的安全部分，不会与互联网接触。
物理设备上的分区存储降低了与连接到 Internet 的设备相关的风险。
但是，由于您依赖的是物理设备，因此丢失设备也意味着无法访问您的数字资产。

在大多数情况下，您可以从硬件钱包的丢失中恢复过来，因为存储在硬件钱包上的资产是使用秘密助记词保护的。
. 如果您复制并保护助记词——例如，以 <<Paper wallets,paper wallet>> 的形式存储它——您可以使用助记词初始化新设备并重新获得对您的数字资产的访问权限。

有关详细信息，请参阅
link:https://cointelegraph.com/explained/crypto-wallets-explained[加密钱包，解释]。

=== 气隙计算机

*气隙计算机*与与互联网交互的不安全网络或家中不安全的局域网隔离。

将标准个人计算机或类似设备转换为气隙计算机可能需要您物理移除网卡、禁用某些软件或准备在再次连接到 Internet 之前彻底擦除计算机。

根据您希望气隙计算机的安全程度，一种选择是使用可启动映像，该映像提供最小的操作系统来收集您的数字资产，然后从该过程中删除任何工件，并在完成任何事务后正常重新启动计算机。
有关更多信息，请参阅link:https://www.wired.com/story/extreme-security-measures/[Extreme Security Measures for the Extra Paranoid] 和
link:https://www.howtogeek.com/687792the-ultimate-defense-what-is-an-air-gapped-computer/[终极防御：什么是气隙计算机？]。

=== 纸钱包

*纸钱包*是一张打印的纸，其中包含您的重要关键信息（在某些情况下，甚至是二维码），用于促进数字资产交易。
通常不推荐使用纸钱包，因为它们容易退化，并且可能不安全、容易丢失或被盗。

但是，作为硬件钱包的备份，您可能希望准备一个纸钱包并将其存储在安全的位置，例如保险箱。

更多信息见link:https://blockgeeks.com/guides/paper-wallet-guide/#Paper_wallets[纸钱包]。

== 保护资产安全

研究可供您使用的冷藏和保管解决方案最终是您的责任。

无论您选择哪种类型的自托管解决方案，您都有责任确保您的数字资产安全。

考虑到这一点，您应该注意以下一般性建议：

* 不要使用工作计算机来配置数字资产存储解决方案。您的私人个人数据可能会丢失或
托管在工作计算机上时受到损害，特别是如果该计算机经常连接到互联网。

* 请勿将您的冷钱包或任何私人信息留在可能被泄露的公共场所。

* 不要丢失您的私钥或助记词。如果丢失，您将永远无法访问您的数字资产。
