= 操作方法：为种子参与者声明神经元
:实验性:
// 为Apple Command键定义统一编码。
:commandkey: &#8984;
:IC: Internet Computer
:company-id: DFINITY
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

_种子贡献者将其 ICP 实用程序令牌声明为 NNS 神经元的指南。 对于在声明后控制神经元，请参阅此
[https://medium.com/dfinity/integrating-ledger-nano-with-the-nns-front-end-dapp-user-manual-9c5600925e16
tutorial]_

== 简介 ==

如果您在 2017 年 2 月向 DFINITY 基金会捐款支持互联网计算机的发展，您就是种子参与者。
那时，每捐赠的价值瑞士法郎 30 个代币将分配给您的钥匙。 这些代币现在被称为“ICP 实用代币”或简称“ICP”。

在 Genesis Unlock，您的 ICP 以一篮子 49 个投票神经元的形式支付给您。这些神经元已经存在于网络神经系统中。您的神经元包含您获得的代币，这些代币被放置在里面。

您的神经元已配置为自动投票，并且已经为您赢得投票奖励。你不需要做任何事情来初始化你的神经元来继续获得投票奖励。

为您创建的 49 个神经元具有 0 天、30 天、60 天、90 天等消除延迟。除了第一个具有 0 天溶解延迟（可以立即溶解）的神经元外，其他溶解延迟可能会添加少量随机天数。

你的神经元也已经提前老化。在创世解锁的那一刻，他们的年龄已经设定为18个月。这很重要，因为神经元年龄显着增加了您的投票权和您获得的投票奖励。

要控制您的神经元，您必须使用捐赠时生成的相同密钥。它被你记录为一个 12 字的助记词。为了控制您的神经元，您需要首先_声明_您的神经元篮。有两种声明方式，本文将在下面进行说明：

* 使用 Ledger Nano 设备进行声明（即将推出）

* 使用气隙计算机 + 联网计算机/智能手机进行声明

声明之后，有两种方法可以控制你的神经元：

* 本文中描述的 NNS dapp (GUI)
link:https://medium.com/dfinity/integrating-ledger-nano-with-the-nns-front-end-dapp-user-manual-9c5600925e16[tutorial]

* 命令行工具 ic-hardware-wallet-cli 在
link:https://github.com/dfinity/nns-dapp/tree/main/ic-hardware-wallet-cli[github]

== 使用 Ledger Nano 设备声明（即将推出）==

这将与 Ledger Nano 的“ICP”应用程序的下一个更新之一一起提供。 当前版本可以管理神经元，但还不能声明它们。

第 1 阶段发布：Ledger Nano 的“ICP”应用程序的第 1 阶段初始版本针对所有消费者。 它允许人们管理神经元，例如更改溶解延迟、溶解、支付、管理热键、投票等。当然，它也允许在原生账本中传输液态 ICP。

第 2 阶段版本：接下来的第 2 阶段版本包括用于种子轮神经元的 `claim_neurons` 函数。 这是专门针对种子轮的人的更新。

== 使用气隙计算机进行声明 ==

声明需要访问您的秘密助记词和从中派生的密钥。 强烈建议您使用气隙计算机进行声明。 如果您对这样的设置或以下任何步骤不满意，那么您必须等待 Ledger Nano 设备的“ICP”应用程序的下一个版本。

作为气隙设备，您可以使用 Windows、Linux 或 MacOS 机器。
Linux 包括树莓派。

=== 下载工具 ===

要下载工具，您需要第二台联网的计算机。 这些工具被称为“keysmith”和“quill”。 我们在这里描述了如何为您的架构查找和下载二进制文件。 或者，您可以从 github 上提供的源代码中自己编译工具
link:https://github.com/dfinity/keysmith[keysmith] 和
link:https://github.com/dfinity/quill[quill].

二进制文件可用于以下硬件架构。 在这里，架构是指气隙计算机，而不是联网计算机。

[options="header"]
|=====
|Hardware |keysmith |quill
|Mac, Intel silicon |darwin-amd64 |macos-x86_64
|Mac, Apple silicon (M1) |darwin-arm64 | -
|Linux (x86) |linux-amd64 |linux-x86_64
|Raspberry Pi |linux-arm32 |arm_32
|Linux (arm) |linux-arm64 | -
|Windows |windows-amd64 |windows-x86_64
|=====

==== 下载keysmith ====

转到link:https://github.com/dfinity/keysmith/releases/[keysmith]，选择最新版本（当前为 v1.6.2）并获取与气隙机器架构匹配的 `.tar.gz` 文件 在上表中。

==== 下载quill ====

转到llink:https://github.com/dfinity/quill/releases[quill], 选择最新版本（必须 >= 0.2.12）并获取与上表中的气隙机架构匹配的可执行文件。

=== 复制到气隙机 ===

将 keysmith `.tar.gz` 文件和 quill 可执行文件从联网机器复制到气隙机。 例如，您可以使用 USB 驱动器执行此操作。

=== 验证哈希 ===

在气隙机上，进入终端。将目录改为存放keysmith .tar.gz文件和quill可执行文件的文件夹。
用以下命令计算SHA256哈希值


[source,bash]
----
openssl dgst -sha256 keysmith-*
----
and
[source,bash]
----
openssl dgst -sha256 quill-*
----

哈希值应与以下条目匹配：
[source,bash]
----
SHA256(keysmith-darwin-amd64.tar.gz)=
a53bad6fa36c1eb35cd36059ffe9cbf4c063b515e47ccf666b7e1c174a7d1088
SHA256(keysmith-darwin-arm64.tar.gz)=
47932452353fe7f921b4ac41828dd19530ae0c4bdb72bcbb016a0715ca80e879
SHA256(keysmith-linux-amd64.tar.gz)=
cb283dac031d8676f25e72d19115be347d2b85c864a17dd563104bf496b14a06
SHA256(keysmith-linux-arm32.tar.gz)=
b28670e2b3483ea9f9ba691e9f76f99df31b2678db33b69c888fb08b634de162
SHA256(keysmith-linux-arm64.tar.gz)=
ebe9cde3cf440ebbfb53dd10bf7f412cbff8b089551100ee0fa48f3ac9bd66c3
SHA256(keysmith-windows-amd64.tar.gz)=
1ef9b77ccaae980aad4a227fe1a817821245da491a90f0e6ad323426b49ae40a
----
和
[source,bash]
----
SHA256(quill-arm_32)=
ebe2506e4dc4422e7670094e8b2b1d854a3b3c317b25c1c88990853d3d85c064
SHA256(quill-linux-x86_64)=
18fc671ee8c96b367875b39470073d68db78d32d242d14d4682025ef2a5d9ad4
SHA256(quill-macos-x86_64)=
97c373ab871be377ac784faff089ca26d23c37725230fb36d78f17d7a73b0867
SHA256(quill-windows-x86_64.exe)=
2542244c9ad3a9baf54bc2227e8c71ea8a8fb9f7e6065cc7a848c7b1cdce906e
----

=== 解压安装 ===

For keysmith:
[source,bash]
----
tar -f keysmith-*.tar* -x
sudo install -d /usr/local/bin
sudo install keysmith /usr/local/bin
----
系统将提示您输入笔记本电脑密码。
密码本身不会出现，只需输入并按回车即可。

For quill:
[source,bash]
----
mv quill-arm_32 quill
sudo install quill /usr/local/bin
----

== 使用 keysmith 生成私钥文件 ==

=== 测试安装 ===

在气隙计算机上运行：
[source,bash]
----
keysmith
----
You should see:
[source,bash]
----
usage: keysmith <command> [<args>]

Available Commands:
account 打印您的帐户标识符。
     generate 生成助记符种子并将其写入文件。
     legacy-address 打印您的旧地址。
     principal 打印您的主体标识符。
     private-key 导出您的私钥并将其写入文件。
     public-key 打印你的公钥。
     shortlist 打印可用的命令。
     version 打印版本号。
     x-private-key 派生您的扩展私钥并将其写入文件。
     x-public-key 打印您的扩展公钥。
----
如果您使用的是 macOS，第一次运行 `keysmith` 可能需要您在系统偏好设置 > 安全和隐私 > 常规下授予权限。

=== 输入您的助记词（又名“种子”）===

如果您确信您的环境是安全的，那么您已经准备好输入您的种子以与“keysmith”一起使用。 在会话期间，您将助记词存储在环境变量中。 当您关闭计算机时，它将从您的系统中删除。

[source,bash]
----
read seed
----
Enter your seed phrase and finish with Return.

如果您不想在键入时显示助记词，请改用以下命令：
[source,bash]
----
read -s seed
----

=== 可选：检查您的旧地址和余额 ===

此时，您已经可以验证您的旧地址和 ICPT 余额。 旧地址与 Dfinity Chrome 扩展程序中以前称为“DFN 地址”的地址匹配。 当您使用扩展程序时，您可能已经从 Chrome 扩展程序中复制了它以供记录。

[source,bash]
----
echo $seed | keysmith legacy-address -f -
----
The output is a 40 character hex string. It looks something like this:

[source,bash]
----
2d89d96b10f7a9456a9154b2f5309ee70df5bce1
----

您可以按如下方式查看您的 ICPT 余额：转到
https://ic.rocks/principal/renrk-eyaaa-aaaaa-aaada-cai，寻找“Canister interface”和“balance”方法。 在那里，将您的 DFN 地址粘贴到标有“文本”的字段中，然后单击标有“查询”的按钮。 您的 ICP 余额将显示在“nat32”下方。

=== 创建您的私钥（.pem 文件）===

从您的助记词中导出您的私钥。
[source,bash]
----
echo $seed | keysmith private-key -f -
----
这会创建一个文件 `identity.pem` 包含您的私人
钥匙。

==== 可选：仅在 RAM 中存储 .pem 文件 ====

稍后我们将从文件系统中擦除 identity.pem 文件。 然而，仍然存在数据可能在磁盘中保留并随后被提取的风险，尽管它已被擦除。 创建 RAM 磁盘并将 .pem 文件仅存储在 RAM 磁盘中更安全。

===== 在 MacOS 上创建 RAM 磁盘 =====

运行这些命令
[source,bash]
----
DISK=$(hdiutil attach -nomount ram://16384)
diskutil erasevolume HFS+ RD $DISK
cd /Volumes/RD
----
before running
[source,bash]
----
echo $seed | keysmith private-key -f -
----

===== 在 Linux 上创建 RAM 磁盘 =====

运行这些命令
[source,bash]
----
sudo mkdir /mnt/ramdisk
sudo mount -t ramfs keysmith /mnt/ramdisk
sudo mkdir /mnt/ramdisk/workspace
sudo chown $USER /mnt/ramdisk/workspace
cd /mnt/ramdisk/workspace
----
before running
[source,bash]
----
echo $seed | keysmith private-key -f -
----

===== 在 Windows 上创建 RAM 磁盘 =====

Todo

== 用quill提交声明 ==

=== 测试安装 ===

在气隙计算机上运行：

[source,bash]
----
quill
----
你应该看到：
[source,bash]
----
quill 0.2.12

Ledger & Governance ToolKit for cold wallets

USAGE:
    quill [OPTIONS] <SUBCOMMAND>

OPTIONS:
    -h, --help Print help information
        --pem-file <PEM_FILE> Path to your PEM file (use "-" for STDIN)
    -V, --version Print version information

SUBCOMMANDS:
    account-balance 查询总账余额
    claim-neurons   从创世代币容器中获取种子神经元
    get-proposal-info
    help            打印此消息或给定子命令的帮助(s)
    list-neurons 对属于signin principal的所有神经元的查询进行签名。
    list-proposals
    neuron-manage 标志着一个神经元配置的改变
    neuron-stake 标志着对一个神经元（新的或现有的）进行充值。
    public-ids 打印委托人ID和账户ID
    send 发送一个签名的消息或一组消息
    transfer 签署一个ICP转移交易
----
如果您使用的是 macOS，请运行 `quill`
第一次可能需要您在系统下授予权限
首选项 > 安全和隐私 > 常规。

=== 签署声明请求 ===

On the air-gapped computer run:
[source,bash]
----
quill --pem-file identity.pem claim-neurons >msg.json
----

=== 向 IC 提交声明 ===

==== 选项 1：在联网计算机上使用 quill ====

将生成的文件“msg.json”复制回联网的计算机。 在联网的计算机上，切换到 `msg.json` 所在的目录并运行：
[source,bash]
----
quill send msg.json
----
你的神经元现在应该被声明了。

您可以通过以下方式仔细检查您声明是否成功：转到 https://ic.rocks/genesis/2d89d96b10f7a9456a9154b2f5309ee70df5bce1，将 `2d89d96b10f7a9456a9154b2f5309ee70df5bce1` 替换为您自己的 DFN 地址。 在“状态”下，您应该看到“已声明”。

==== 选项 2：使用 QR 扫描应用程序 ====

* Install `qrencode`

* Run `cat msg.json | gzip -c | base64 | qrencode -o msg.png`

* 在图像查看器中打开 `msg.png`

* 在手机浏览器中打开扫描仪应用程序：
https://p5deo-6aaaa-aaaab-aaaxq-cai.raw.ic0.app

* 扫描二维码并提交

===清理气隙计算机===

如果您的声明成功，请不要忘记删除气隙计算机上的“.pem”文件：

[source,bash]
----
rm identity.pem
----
