= dfx cache

使用带有标志和子命令的 `+dfx cache+` 命令来管理 `+dfx+` 版本缓存。

运行 `+dfx cache+` 命令的基本语法是:

[source,bash]
----
dfx cache [subcommand] [flag]
----

根据您指定的 `+dfx cache+` 子命令，可能会应用其他参数、选项和标志。
有关说明使用 `+dfx cache+` 命令的参考信息和示例，请选择适当的命令。

[width="100%",cols="<32%,<68%",options="header"]
|===
|命令 |描述
|<<dfx cache delete,`+delete+`>> |从本地缓存中删除指定版本的 `+dfx+`。

|`+help+` |显示指定子命令的帮助信息消息。

|<<dfx cache install,`+install+`>> |从本地缓存安装指定版本的 `+dfx+`。

|<<dfx 缓存列表,`+list+`>> |列出当前项目中当前安装和使用的 `+dfx+` 的版本。

|<<dfx cache show,`+show+`>> |显示此版本的 `+dfx+` 可执行文件使用的缓存路径。
|===

要查看特定子命令的帮助信息，请指定子命令和 `+--help+` 标志。
例如，要查看 `+dfx cache delete+` 的帮助信息，可以运行以下命令:

[source,bash]
----
dfx cache delete --help
----

[[delete]]
== dfx cache delete

使用 `+dfx cache delete+` 命令从本地计算机的版本缓存中删除特定版本的 `+dfx+`

=== 基本用法

[source,bash]
----
dfx cache delete [version] [flag]
----

=== Flags

您可以在 `+dfx cache delete+` 命令中使用以下可选标志。

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |显示帮助信息
|`+-V+`, `+--version+` |显示版本信息
|===

=== 参数

您可以为 `+dfx cache delete+` 命令指定以下参数。

[width="100%",cols="<32%,<68%",options="header"]
|===
|命令 |描述
|`+version+` |指定要从本地缓存中删除的 `+dfx+` 的版本。
|===

=== 例子

您可以使用 `+dfx cache delete+` 命令永久删除不想再使用的 `+dfx+` 版本。
例如，您可以运行以下命令删除 `+dfx+` 版本 `+0.6.2+`:

[source,bash]
----
dfx cache delete 0.6.2
----

[[install]]
== dfx 缓存安装

使用 `+dfx cache install+` 命令安装 `+dfx+`，使用当前在 `+dfx+` 缓存中找到的版本。

=== 基本用法

[source,bash]
----
dfx cache install [flag]
----

=== 标志

您可以在 `+dfx cache install+` 命令中使用以下可选标志。

[width="100%",cols="<32%,<68%",options="header"]
|===
|标志 |说明
|`+-h+`, `+--help+` |显示帮助信息
|`+-V+`, `+--version+` |显示版本信息
|===

=== 例子

您可以使用 `+dfx cache install+` 命令从缓存中的版本强制安装 `+dfx+`。
例如，您可以运行以下命令来安装 `+dfx+`:

[source,bash]
----
dfx cache install
----

== dfx 缓存列表

使用 `+dfx cache list+` 命令列出您当前在项目中安装和使用的 `+dfx+` 版本。

如果您安装了多个版本的 `+dfx+`，缓存列表会显示一个星号 (*) 以指示当前活动的版本。

=== Basic usage

[source,bash]
----
dfx cache list [flag]
----

=== 标志

您可以在 `+dfx cache list+` 命令中使用以下可选标志。

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |显示帮助信息
|`+-V+`, `+--version+` |显示版本信息
|===

=== Examples

您可以使用 `+dfx cache list+` 命令列出您当前在项目中安装和使用的 `+dfx+` 版本。
例如，您可以运行以下命令来列出在缓存中找到的 `+dfx+` 的版本:

[source,bash]
----
dfx cache list
----

此命令显示找到的 `+dfx+` 版本列表，类似于以下内容:

[source,bash]
----
0.6.4 *
0.6.3
0.6.0
----

== dfx cache show

使用 `+dfx cache show+` 命令显示您当前使用的 `+dfx+` 版本使用的缓存的完整路径。

=== 基本用法

[source,bash]
----
dfx cache show [flag]
----

=== 标志

您可以在 `+dfx cache show+` 命令中使用以下可选标志。

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |显示帮助信息
|`+-V+`, `+--version+` |显示版本信息
|===

=== 例子

您可以使用 `+dfx cache show+` 命令显示您当前使用的 `+dfx+` 版本使用的缓存的路径:

[source,bash]
----
dfx cache show
----

此命令显示您当前使用的 `+dfx+` 版本使用的缓存路径：

[source,bash]
----
/Users/pubs/.cache/dfinity/versions/0.6.4
----

