= dfx 容器

使用带有标志和子命令的 `+dfx canister+` 命令来管理容器操作以及与 {platform} 或本地容器执行环境的交互。
在大多数情况下，您在编译程序后使用 `+dfx canister+` 子命令来管理容器生命周期并执行关键任务，例如调用程序函数。

运行 `+dfx canister+` 命令的基本语法是：

[source,bash]
----
dfx canister [subcommand] [flag]
----

根据您指定的 `+dfx canister+` 子命令，可能会应用或需要其他参数、选项和标志。
要查看特定 `+dfx canister+` 子命令的使用信息，请指定子命令和 `+--help+` 标志。
例如，要查看 `+dfx canister call+` 的使用信息，可以运行以下命令：

[source,bash]
----
dfx canister call --help
----

有关说明使用 `+dfx canister+` 命令的参考信息和示例，请选择适当的命令。

[width="100%",cols="<32%,<68%",options="header"]
|===
|命令 |描述
|<<dfx canister call,`+call+`>> |调用已部署容器上的指定方法。

|<<dfx canister create,`+create+`>> |通过在 {platform} 或本地容器执行环境上注册容器标识符来创建新的“空”容器。

|<<dfx canister delete,`+delete+`>> |删除当前停止的容器。

|`+help+` |显示指定子命令的使用信息消息。

|<<dfx canister id,`+id+`>> |显示容器的标识符。

|<<dfx canister install,`+install+`>> |将编译后的代码作为容器安装在 {platform} 或本地容器执行环境中。

|<<dfx canister request-status,`+request-status+`>> |请求容器的调用状态。

|<<dfx canister set-controller,`+set-controller+`>> |指定要用作 {platform} 上指定容器的新控制器的身份名称或主体。

|<<dfx canister send,`+send+`>> |将先前签名的 `+message.json+` 发送到指定的容器标识符。 例如，如果您想发送一条调用网络神经系统 (NNS) 治理容器来管理神经元的消息，出于安全原因，您可能希望将消息签名与消息传递分开。

|<<dfx canister send,`+sign+`>> |在调用指定的容器标识符之前创建一个签名的 `+message.json+` 文件。 例如，如果您想发送一条调用网络神经系统 (NNS) 治理容器来管理神经元的消息，出于安全原因，您可能希望将消息签名与消息传递分开。

|<<dfx canister start,`+start+`>> |重新启动停止的容器。

|<<dfx canister status,`+status+`>> |请求容器的运行状态。

|<<dfx canister stop,`+stop+`>> |停止当前正在运行的容器。

|===

== 覆盖默认部署环境

默认情况下，`+dfx canister+` 命令在 `+dfx.json+` 文件中指定的本地容器执行环境中运行。
如果您想在不更改 `+dfx.json+` 配置文件中的设置的情况下向 {platform} 或测试网发送 `+dfx canister+` 子命令，则可以使用 `+-- 显式指定要连接的 URL 网络+`选项。

例如，要在本地容器执行环境中为项目注册唯一容器标识符，您可以运行以下命令：

[source,bash]
----
dfx canister create --all
----

如果要在 {platform} 上为同一项目注册唯一容器标识符，可以运行以下命令：

[source,bash]
----
dfx canister --network ic create --all
----

{sdk-short-name} 带有一个别名 `+ic+`，它被配置为指向 {platform}。 您还可以将 URL 作为网络选项传递，或者您可以在 `+networks+` 配置下的 `+dfx.json+` 中配置其他别名。

为了说明，您可以使用类似于以下的命令调用在测试网上运行的容器和函数：

[source,bash]
----
dfx canister --network \http://192.168.3.1:5678 call counter get
----

请注意，您必须在容器操作（`+create+` 或 `+call+`）之前指定 `+--network+` 参数以及任何其他参数，例如容器名称（`+counter+`）和函数（`+get+ `）。

== dfx 容器调用

使用 `+dfx canister call+` 命令调用已部署容器上的指定方法。

=== 基本用法

[source,bash,subs="quotes"]
----
dfx canister call [option] _canister_name_ _method_name_ [argument] [flag]
----

=== 标志

您可以在 `+dfx canister call+` 命令中使用以下可选标志。

[width="100%",cols="<31%,<69%",options="header"]
|===
|标志 |说明
|`+--async+` |通过轮询本地容器执行环境或{platform}，使您无需等待返回调用结果即可继续。

|`+-h+`, `+--help+` |显示使用信息。

|`+--query+` |使您能够向已部署的容器发送查询请求。
为了获得最佳性能，当您明确想要使用查询方法检索信息时，您应该使用此标志。
有关查询和更新调用之间差异的信息，请参阅link：../concepts/canisters-code{outfilesuffix}#canister-state[容器包括程序和状态]。

|`+--update+` |使您能够向已部署的容器发送更新请求。
默认情况下，容器调用使用更新方法。

|`+-V+`, `+--version+` |显示版本信息。
|===

=== 选项

您可以在 `+dfx canister call+` 命令中使用以下选项。

[width="100%",cols="<31%,<69%",options="header"]
|===
|选项 |说明

|`+--output <output>+` |指定显示方法返回结果时使用的输出格式。
有效值为 `+idl+` 和 `+raw+`。

|`+--type <type>+` |使用参数进行调用时指定参数的数据格式。
有效值为 `+idl+` 和 `+raw+`。
|===

=== 参数

您可以为 `+dfx canister call+` 命令指定以下参数。

[width="100%",cols="<31%,<69%",options="header",]
|===
|`+canister_name+` |指定要调用的容器的名称。 容器名称是必需的参数，并且应该与您在 `+dfx.json+` 配置文件的 `+canisters+` 部分中为项目配置的名称匹配。


|`+method_name+` |指定要在容器上调用的方法名称。
canister 方法是必需的参数。

|`+argument+` |指定要传递给方法的参数。
根据您的程序逻辑，参数可以是必需参数或可选参数。
如果将参数传递给容器，则可以使用 `+--type+` 选项指定数据格式类型。
默认情况下，您可以使用以下链接指定参数link：../../candid-guide/candid-intro{outfilesuffix}[Candid] (`+idl+`) 数据值语法。
有关使用 Candid 及其支持的类型的信息，请参阅链接link：../../candid-guide/candid-howto{outfilesuffix}#idl-syntax[与终端中的服务交互] 和link：../.. /candid-guide/candid-types{outfilesuffix}[支持的类型]。
如果要将原始字节传递给容器，可以使用 `+raw+` 作为参数类型。
|===

=== 例子

在使用 `+dfx canister install+` 命令部署容器后，可以使用 `+dfx canister call+` 命令调用特定方法（带或不带参数）。
例如，要为 `+canister_name+` 为 `+counter+` 的容器调用 `+get+` 方法，可以运行以下命令：

[source,bash]
----
dfx canister call counter get --async
----

在此示例中，该命令包含 `+--async+` 选项以指示您要进行单独的 `+request-status+` 调用，而不是等待轮询本地容器执行环境或 {platform} 以获取结果。
当处理操作可能需要一些时间才能完成时，`+--async+` 选项很有用。
该选项使您能够继续执行其他操作，然后使用单独的 `+dfx canister request-status+` 命令检查结果。
返回的结果将显示为 IDL 文本格式。

==== 使用 IDL 语法

您可以通过对 Text 数据类型运行类似于以下的命令来显式指定使用 IDL 语法传递参数：

[source,bash]
----
dfx canister call hello greet --type idl '("Lisa")'
("Hello, Lisa!")

dfx canister call hello greet '("Lisa")' --type idl
("Hello, Lisa!")
----

您还可以通过运行类似于以下的命令来隐式使用 IDL：

[source,bash]
----
dfx canister call hello greet '("Lisa")'
("Hello, Lisa!")
----

要使用 IDL 语法指定多个参数，请在参数之间使用逗号。
例如：

[source,bash]
----
dfx canister call contacts insert '("Amy Lu","01 916-335-2042")'

dfx canister call hotel guestroom '("Deluxe Suite",42,true)'
----

您可以通过运行类似于以下内容的命令以字节为单位传递原始数据：

[source,bash]
----
dfx canister call hello greet --type raw '4449444c00017103e29883'
----

此示例使用原始数据类型将十六进制传递给 `+hello+` 容器的 `+greet+` 函数。

== dfx 容器创建

使用 `+dfx canister create+` 命令注册一个或多个容器标识符，无需编译代码。
您必须连接到本地容器执行环境或 {platform} 才能运行此命令。

请注意，您只能从项目目录结构中运行此命令。
例如，如果您的项目名称是 `+hello_world+`，那么您当前的工作目录必须是 `+hello_world+` 顶级项目目录或其子目录之一。

第一次运行 `+dfx canister create+` 命令注册标识符时，您的公钥/私钥对凭据将用于创建 `+default+` 用户身份。
`+default+` 用户的凭据从 `+$HOME/.dfinity/identity/creds.pem+` 迁移到 `+$HOME/.config/dfx/identity/default/identity.pem+`。

=== 基本用法

[source,bash,subs="quotes"]
----
dfx canister create [option] [flag] [--all | _canister_name_]
----

=== 标志

您可以在 `+dfx canister create+` 命令中使用以下可选标志。

[width="100%",cols="<31%,<69%",options="header"]
|===
|标志 |说明

|`+-h+`, `+--help+` |显示使用信息。

|`+-V+`, `+--version+` |显示版本信息。
|===

=== 选项

您可以在 `+dfx canister create+` 命令中使用以下选项。

[width="100%",cols="<31%,<69%",options="header"]
|===
|`+--with-cycles <number-of-cycles>+` |允许您在钱包创建容器时指定容器中的初始周期数。
|===

=== 参数

您可以在 `+dfx canister create+` 命令中使用以下参数。

[width="100%",cols="<31%,<69%",options="header"]
|===
|参数 |描述
|`+--all+` |如果您有一个定义多个容器的项目“+dfx.json+”文件，则使您能够一次创建多个容器标识符。
请注意，您必须指定 `+--all+` 或单个容器名称。
|`+canister_name+` |指定要为其注册标识符的容器的名称。
如果您不使用 `+--all+` 选项，则容器名称是必需的参数，并且必须与您在 `+dfx.json+` 配置文件的 `+canisters+` 部分中配置的至少一个名称匹配 你的项目。
|===

=== 例子

您可以使用 `+dfx canister create+` 命令注册容器标识符，而无需先编译任何代码。
例如，如果要在编写程序之前为项目`+my_counter+`创建容器标识符，可以运行以下命令：

[source,bash]
----
dfx canister create my_counter
----

您可以使用带有 `+--with-cycles+` 选项的 `+dfx canister create+` 命令来指定在项目中创建一个或所有容器时的初始平衡。 例如，要为所有容器指定 8000000000000 个循环的初始平衡，请运行以下命令：

[source,bash]
----
dfx canister create --with-cycles 8000000000000 --all
----

== dfx 容器删除

使用 `+dfx canister delete+` 命令从本地容器执行环境或 {platform} 上删除已停止的容器。

请注意，您只能从项目目录结构中运行此命令。
例如，如果您的项目名称是 `+hello_world+`，那么您当前的工作目录必须是 `+hello_world+` 顶级项目目录或其子目录之一。

=== 基本用法

[source,bash,subs="quotes"]
----
dfx canister delete [flag] [--all | _canister_name_]
----

=== 标志

您可以在 `+dfx canister delete+` 命令中使用以下可选标志。

[width="100%",cols="<31%,<69%",options="header"]
|===
|Flag |描述

|`+-h+`, `+--help+` |显示使用信息。

|`+-V+`, `+--version+` |显示版本信息。
|===

=== 参数

您可以在 `+dfx canister delete+` 命令中使用以下参数。

[width="100%",cols="<31%,<69%",options="header"]
|===
请注意，您必须指定容器名称或 `+--all+` 选项。
|===

=== 例子
您可以使用 `+dfx canister delete` 命令删除特定容器或所有容器。
要删除 `+hello_world` 容器，可以运行以下命令：

[source,bash]
----
dfx canister delete hello_world
----

要删除您在 `+ic+` {platform} 上部署的所有容器，可以运行以下命令：

[source,bash]
----
dfx canister --network=ic delete --all
----

== dfx canister id

使用 `+dfx canister id+` 命令输出特定容器名称的容器标识符。

请注意，您只能从项目目录结构中运行此命令。
例如，如果您的项目名称是 `+hello_world+`，那么您当前的工作目录必须是 `+hello_world+` 顶级项目目录或其子目录之一。

=== 基本用法

[source,bash,subs="quotes"]
----
dfx canister id [flag] _canister_name_
----

=== 标志

您可以在 `+dfx canister id+` 命令中使用以下可选标志。

[width="100%",cols="<31%,<69%",options="header"]
|===
|标志 |说明

|`+-h+`, `+--help+` |显示使用信息。

|`+-V+`, `+--version+` |显示版本信息。
|===

=== 参数

您可以在 `+dfx canister id+` 命令中使用以下参数。

[width="100%",cols="<31%,<69%",options="header"]
|===
|参数 |描述

|`+canister_name+` |指定要显示其标识符的容器的名称。

|===

=== 例子

您可以使用 `+dfx canister id+` 命令显示特定容器名称的容器标识符。

要显示 `+hello_world+` 容器的容器标识符，可以运行以下命令：

[source,bash]
----
dfx canister id hello_world
----

该命令显示类似于以下内容的输出：

[source,bash]
----
75hes-oqbaa-aaaaa-aaaaa-aaaaa-aaaaa-aaaaa-q
----

== dfx 容器安装

使用 `+dfx canister install+` 命令将编译后的代码作为容器安装在 {platform} 或本地容器执行环境中。

=== 基本用法

[source,bash,subs="quotes"]
----
dfx canister install [flag] [option] [--all | _canister_name_]
----

=== 标志

您可以在 `+dfx canister install+` 命令中使用以下可选标志。

[width="100%",cols="<31%,<69%",options="header"]
|===
|标志 |说明

|`+--async+` |通过轮询 {platform} 或本地容器执行环境，使您无需等待返回安装结果即可继续。

|`+-h+`, `+--help+` |显示使用信息。

|`+-V+`, `+--version+` |显示版本信息。
|===

=== 选项

您可以在 `+dfx canister install+` 命令中使用以下选项。

[width="100%",cols="<31%,<69%",options="header"]
|===
|Option |Description
|`+--argument <argument>+` |指定在安装期间传递给容器的参数。

|`+--argument-type <argument-type>+` |使用 `+--argument+` 选项安装时指定参数的数据格式。 有效值为 `+idl+` 和 `+raw+`。
默认情况下，您可以使用以下链接指定参数link：../../candid-guide/candid-intro{outfilesuffix}[Candid] (`+idl+`) 数据值语法。
有关使用 Candid 及其支持的类型的信息，请参阅link：../../candid-guide/candid-howto{outfilesuffix}#idl-syntax[与终端中的服务交互] 和link：../.. /candid-guide/candid-types{outfilesuffix}[支持的类型]。
如果要将原始字节传递给容器，可以使用 `+raw+` 作为参数类型。

|`+-c+`, `+--compute-allocation <compute-allocation>+` |为容器执行定义计算分配（本质上相当于设置 CPU 分配）。
您可以将此值设置为 0 到 100 范围内的百分比。

|`+--memory-allocation <memory-allocation>+` |指定容器总共允许使用多少内存。
您可以在 0 到 8MB 的范围内设置此值。

|`+-m+`, `+--mode <mode>+` |指定您是要`+install+`、`+reinstall+` 还是`+upgrade+` 容器。
有关安装模式和容器管理的更多信息，请参阅link：../working-with-canisters{outfilesuffix}[管理容器]。

|===

=== 参数

您可以在 `+dfx canister install+` 命令中使用以下参数。

[width="100%",cols="<31%,<69%",options="header"]
|===
|参数 |描述

|`+--all+` |如果您有一个包含多个容器的项目“dfx.json”文件，则允许您一次安装多个容器。
请注意，您必须指定 `--all` 或单个容器名称。

|`+canister_name+` |指定要部署的容器的名称。
如果您没有使用 `+--all+` 选项，则容器名称是必需的参数，并且应该与您在 `+dfx.json+` 配置文件的 `+canisters+` 部分中为项目配置的名称相匹配。
|===

=== 例子

您可以使用 `+dfx canister install+` 命令将使用 `+dfx build+` 命令编译的 WebAssembly 部署为 {platform} 或本地容器执行环境上的容器。
最常见的用例是通过运行以下命令来安装所有容器：

[source,bash]
----
dfx canister install --all
----

==== 安装特定的容器

您还可以使用 `+dfx canister install+` 命令部署特定的容器，而不是项目中的所有容器。
例如，如果您有一个带有 `+hello_world+` 容器和 `+hello_world_assets+` 容器的项目，但只想部署 `+hello_world+` 容器，则可以通过运行以下命令仅部署该容器：

[source,bash]
----
dfx canister install hello_world
----

==== 发送异步请求

如果您想提交安装容器的请求并返回请求标识符以稍后检查您的请求状态，而不是等待命令完成，您可以运行类似于以下的命令：
[source,bash]
----
dfx canister install hello_world --async
----

此命令提交安装容器的请求并返回类似于以下内容的请求标识符：
[source,bash]
----
0x58d08e785445dcab4ff090463b9e8b12565a67bf436251d13e308b32b5058608
----

然后，您可以稍后使用请求标识符来检查请求的状态，就像您运送包裹时的跟踪号一样。

==== 覆盖默认部署选项

如果您想在不更改 `+dfx.json+` 配置文件中的设置的情况下在测试网上部署容器，可以使用 `+--network` 选项明确指定要连接的测试网。

例如，您可以通过运行类似于以下的命令来指定测试网 URL：

[source,bash]
----
dfx canister --network \http://192.168.3.1:5678 install --all
----

请注意，您必须在容器操作 (`+install+`) 和容器名称或 `+--all+` 标志之前指定网络参数。

==== 分配消息处理

`+--compute-allocation+` 选项允许您将计算资源分配为 0 到 100 范围内的百分比，以指示您的容器应该多久安排一次执行。

例如，假设您运行以下命令：

[source,bash]
----
dfx canister install --all --compute-allocation 50
----

使用此设置，当前项目中的所有容器都分配有 50%。 当项目中的容器接收到要处理的输入消息时，这些消息将被安排执行。
超过 100 个执行周期，每个容器的消息将被安排处理至少 50 次。

此选项的默认值为 0 — 表示没有特定的分配或调度生效。
如果您的所有容器都使用默认设置，则以循环方式进行处理。


== dfx 容器请求状态

使用 `+dfx canister request-status+` 命令请求对容器的指定调用的状态。
此命令要求您指定在容器上调用方法后收到的请求标识符。
请求标识符是一个以 `+0x+` 开头的十六进制字符串。

=== 基本用法

[source,bash,subs="quotes"]
----
dfx canister request-status _request_id_
----

=== 标志

您可以在 `+dfx canister request-status+` 命令中使用以下可选标志。

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |显示使用信息。
|`+-V+`, `+--version+` |显示版本信息。
|===

=== 参数

您可以为 `+dfx canister request-status+` 命令指定以下参数。

[width="100%",cols="<32%,<68%",options="header"]
|===
|参数 |描述
|`+request_id+` |指定响应`+dfx canister call+`或`+dfx canister install+`命令返回的十六进制字符串。
此标识符是一个以 0x 开头的十六进制字符串。
|===

=== 例子

您可以使用 `+dfx canister request-status+` 命令检查容器状态更改的状态，或者通过运行类似于以下的命令来验证呼叫未被拒绝：

[source,bash]
----
dfx canister request-status 0x58d08e785445dcab4ff090463b9e8b12565a67bf436251d13e308b32b5058608
----

如果请求标识符无效或被容器拒绝，此命令将显示错误消息。

== dfx 容器组控制器

使用 `+dfx canister set-controller+` 命令指定身份名称或主体以用作 {platform} 上指定容器的新 **controller**。
控制器身份具有管理其控制的容器的特殊权限。
例如，只能使用控制身份来安装、升级或删除其控制下的容器。

请注意，您可以将用户身份或容器指定为控制器。
您还可以通过使用其名称或其主体来指定控制器身份。

=== 基本用法

[source,bash,subs="quotes"]
----
dfx canister set-controller [flag] _canister_ _new-controller_
----

=== 标志

您可以在 `+dfx canister set-controller+` 命令中使用以下可选标志。

[width="100%",cols="<31%,<69%",options="header"]
|===
|标志 |说明

|`+-h+`, `+--help+` |显示使用信息。

|`+-V+`, `+--version+` |Displays version information.
|===

=== 参数

您必须在 `+dfx canister set-controller+` 命令中使用以下参数。

[width="100%",cols="<31%,<69%",options="header"]
|===
|参数 |描述

|`+<canister>+` |指定由您使用_new_controller_ 参数指定的身份控制的容器名称或容器标识符。

|`+<new_controller>+` |指定控制器的身份名称或主体。
|===

=== 例子

您可以使用 `+dfx canister set-controller+` 命令将用户或容器指定为特定容器的控制标识。

例如，您可以创建一个名为 `+pubsadmin+` 的新身份，然后运行 `+dfx canister set-controller+` 以指定您希望 `+pubsadmin+` 身份成为 `+hello_world+` 容器的控制器，方法是运行 以下命令：

....
dfx identity new pubsadmin
dfx canister set-controller hello_world pubsadmin
....

要使用身份主体的文本表示来设置控制身份，您可以运行类似于以下内容的命令：

....
dfx canister set-controller hello_world wcp5u-pietp-k5jz4-sdaaz-g3x4l-zjzxa-lxnly-fp2mk-j3j77-25qat-pqe
....

尽管指定用户身份名称或委托人是一个潜在的用例，但更常见的场景是指定要用于向容器发送周期的钱包容器。
以下步骤说明了您进行本地开发时的这种情况。 对于此示例，假设您创建了一个名为“open_sf”的项目，其中两个容器部署在本地容器执行环境中。

. 创建一个身份——例如，`sf-controller`——作为控制器。
+
....
dfx identity new sf-controller

Creating identity: "sf-controller".
Created identity: "sf-controller".
....
. 使新身份成为活动身份。
+
....
dfx identity use sf-controller

Using identity: "sf-controller".
....
. 为新身份生成钱包容器标识符。
+
....
dfx identity get-wallet

在本地容器执行环境中创建钱包容器。
r7inp-6aaaa-aaaaa-aaabq-cai
用户“sf-controller”的本地容器执行环境上的钱包容器是“r7inp-6aaaa-aaaaa-aaabq-cai”
....
. 将活动标识切换到容器的当前控制器。 例如，如果使用默认身份创建容器，您将运行以下命令：
+
....
dfx identity use default

Using identity: "default".
....
. 将指定容器的控制器设置为使用与 sf-controller 身份关联的钱包。
+
....
dfx 容器组控制器 open_sf_assets r7inp-6aaaa-aaaaa-aaabq-cai

将“r7inp-6aaaa-aaaaa-aaabq-cai”设置为“open_sf_assets”的控制器。
....
+
您现在可以使用钱包容器“r7inp-6aaaa-aaaaa-aaabq-cai”发送燃料费或将保管人添加到“open_sf_assets”容器。

== dfx 容器发送 ==

当您想要分离这些步骤时，在使用 `+dfx canister sign+` 命令签署消息后使用 `+dfx canister send+` 命令，而不是使用单个 `+dfx canister call+` 命令。 使用单独的调用可以增加事务的安全性。

例如，在创建神经元股权时，您可能希望使用 `+dfx canister sign+` 命令使用气隙计算机创建签名的 `+message.json+` 文件，然后使用 `+dfx canister send+` 命令 传递签名的消息。  

=== 基本用法

[source,bash,subs="quotes"]
----
dfx canister send _file_name_
----

=== 标志

您可以在 `+dfx canister request-status+` 命令中使用以下可选标志。

[width="100%",cols="<32%,<68%",options="header"]
|===
|标志 |说明
|`+-h+`, `+--help+` |显示使用信息。
|`+-V+`, `+--version+` |显示版本信息。
|===

=== 参数

您可以为 `+dfx canister send+` 命令指定以下参数。

[width="100%",cols="<32%,<68%",options="header"]
|===
|参数 |描述
|`+file_name+` |指定消息的文件名。
|===

=== 例子

使用 `+dfx canister send+` 命令将使用 `+dfx canister sign+` 命令创建的签名消息发送到创世代币容器 (GTC)，以通过运行以下命令代表您创建神经元：

`+dfx canister send message.json+`

== dfx 容器标志 ==

当您想要分离这些步骤时，在使用 `+dfx canister send+` 命令发送消息之前使用 `+dfx canister sign+` 命令，而不是使用单个 `+dfx canister call+` 命令。 使用单独的调用可以增加事务的安全性。
例如，在创建神经元股权时，您可能希望使用 `+dfx canister sign+` 命令使用气隙计算机创建签名的 `+message.json+` 文件，然后使用 `+dfx canister send+` 命令 从连接到 {platform} 的计算机传递签名消息。

=== 基本用法

[source,bash,subs="quotes"]
----
dfx canister sign [flag] [option] _canister-name_ _method-name_ [argument]
----

=== 标志

您可以在 `+dfx canister sign+` 命令中使用以下可选标志。

[width="100%",cols="<32%,<68%",options="header"]
|===
|标志 |说明
|`+-h+`, `+--help+` |显示使用信息。
|`+--query+` |向容器发送查询请求。
|`+--update+` |向容器发送更新请求。 如果不使用 `+--query+` 方法，这是默认方法。
|`+-V+`, `+--version+` |显示版本信息。
|===

=== 选项

您可以为 `+dfx canister sign+` 命令指定以下选项。

[width="100%",cols="<32%,<68%",options="header"]
|===
|选项 |说明
|`+--expire-after <expire-after>+` |指定在过期和无法发送之前有效的时间。 以秒为单位指定。 如果不定义，默认为300s（5m）
|`+--file <file>+` |指定输出文件名。 默认是`+message.json+`。
|`+--random <random>+` |指定生成随机参数的配置。
|`+--type <type>+` |使用参数进行调用时指定参数的数据类型。

默认情况下，您可以使用以下链接指定参数link：../../candid-guide/candid-intro{outfilesuffix}[Candid] (`+idl+`) 数据值语法。
有关使用 Candid 及其支持的类型的信息，请参阅link：../../candid-guide/candid-howto{outfilesuffix}#idl-syntax[与终端中的服务交互] 和link：../.. /candid-guide/candid-types{outfilesuffix}[支持的类型]。
如果要传递原始字节，可以使用 `+raw+` 作为参数类型。
|===

=== 参数

您可以为 `+dfx canister sign+` 命令指定以下参数。

[width="100%",cols="<32%,<68%",options="header"]

|===
|参数 |描述
|`+canister_name+` |指定要调用的容器的名称。 容器名称是必需的参数，并且应该与您在 `+dfx.json+` 配置文件的 `+canisters+` 部分中为项目配置的名称匹配。

|`+method_name+` |指定要在容器上调用的方法名称。
canister 方法是必需的参数。

|`+argument+` |指定要传递给方法的参数。
根据您的程序逻辑，参数可以是必需参数或可选参数。
如果将参数传递给容器，则可以使用 `+--type+` 选项指定数据格式类型。
默认情况下，您可以使用以下链接指定参数link：../../candid-guide/candid-intro{outfilesuffix}[Candid] (`+idl+`) 数据值语法。
有关使用 Candid 及其支持的类型的信息，请参阅link：../../candid-guide/candid-howto{outfilesuffix}#idl-syntax[与终端中的服务交互] 和link：../.. /candid-guide/candid-types{outfilesuffix}[支持的类型]。
如果要传递原始字节，可以使用 `+raw+` 作为参数类型。
|===

=== 例子

使用 `+dfx canister sign+` 命令创建一个签名的 `message.json` 文件，该文件使用与您使用隐私增强邮件 (PEM) 文件创建的身份相关联的主体，方法是运行类似于以下内容的命令：

`+dfx canister --network=ic sign --expire-after=1h rno2w-sqaaa-aaaaa-aaacq-cai create_neurons ‘(“PUBLIC_KEY”)’+`

该命令说明了如何创建一个 `+message.json+` 文件以在由 `+ic+` 别名指定的 {platform} 上创建神经元，该别名使用您的主体标识符作为消息发送者进行签名，并且到期窗口结束于一小时。

请注意，分配给发送签名消息的时间是固定的 5 分钟窗口。 `+--expire-after+` 选项使您能够指定发送签名消息的 5 分钟窗口应该结束的时间点。 例如，如果您将 `+--expire-after+` 选项设置为一小时（`+1h+`），则必须等待至少 55 分钟才能发送生成的消息，并且消息的签名仅在 5 分钟窗口在第 60 分钟结束。

因此，在此示例中，您需要在 55 分钟之后和 60 分钟之前发送消息，才能将消息识别为有效。

如果您不指定 `+--expire-after+` 选项，则默认过期时间为 5 分钟。

通过运行以下命令将签名的消息发送到创世代币容器 (GTC) 以代表您创建神经元：

`+dfx canister send message.json+`

== dfx 容器启动

使用 `+dfx canister start+` 命令在 {platform} 或本地容器执行环境中重新启动已停止的容器。

在大多数情况下，您在停止容器后运行此命令以正确终止任何挂起的请求，这是升级容器的先决条件。

请注意，您只能从项目目录结构中运行此命令。
例如，如果您的项目名称是 `+hello_world+`，那么您当前的工作目录必须是 `+hello_world+` 顶级项目目录或其子目录之一。

=== 基本用法

[source,bash,subs="quotes"]
----
dfx canister start [flag] [--all | _canister_name_]
----

=== 标志

您可以在 `+dfx canister start+` 命令中使用以下可选标志。

[width="100%",cols="<31%,<69%",options="header"]
|===
|标志 |说明

|`+-h+`, `+--help+` |显示使用信息。

|`+-V+`, `+--version+` |显示版本信息。
|===

=== 参数

您可以在 `+dfx canister start+` 命令中使用以下参数。

[width="100%",cols="<31%,<69%",options="header"]
|===
|参数 |描述

|`+--all+` |启动在`+dfx.json+`文件中配置的所有容器。 请注意，您必须指定 `+--all+` 或单个容器名称。

|`+canister_name+` |指定要启动的容器的名称。
请注意，您必须指定容器名称或 `+--all+` 选项。
|===

=== 例子

您可以使用 `+dfx canister start+` 命令启动特定容器或所有容器。

要启动 `+hello_world+` 容器，可以运行以下命令：

[source,bash]
----
dfx canister start hello_world
----

要启动您在 `+ic+` {platform} 上部署的所有容器，可以运行以下命令：

[source,bash]
----
dfx canister --network=ic start --all
----

== dfx 容器状态

使用 `+dfx canister status+` 命令检查容器当前是否正在运行、正在停止或当前在 {platform} 或本地容器执行环境中停止。

请注意，您只能从项目目录结构中运行此命令。
例如，如果您的项目名称是 `+hello_world+`，那么您当前的工作目录必须是 `+hello_world+` 顶级项目目录或其子目录之一。

=== 基本用法

[source,bash,subs="quotes"]
----
dfx canister status [flag] [--all | _canister_name_]
----

=== 标志

您可以在 `+dfx canister status+` 命令中使用以下可选标志。

[width="100%",cols="<31%,<69%",options="header"]
|===
|标志 |说明

|`+-h+`, `+--help+` |显示使用信息。

|`+-V+`, `+--version+` |显示版本信息。
|===

=== 参数

您可以在 `+dfx canister status+` 命令中使用以下参数。

[width="100%",cols="<31%,<69%",options="header"]
|===
|参数 |描述

|`+--all+` |返回在`+dfx.json+`文件中配置的所有容器的状态信息。 请注意，您必须指定 `+--all+` 或单个容器名称。

|`+canister_name+` |指定要为其返回信息的容器的名称。
请注意，您必须指定容器名称或 `+--all+` 选项。
|===

=== 例子

您可以使用 `+dfx canister status+` 命令检查特定容器或所有容器的状态。

要检查 `+hello_world+` 容器的状态，可以运行以下命令：

[source,bash]
----
dfx canister status hello_world
----

要检查您在 `+ic+` {platform} 上部署的所有容器的状态，可以运行以下命令：

[source,bash]
----
dfx canister --network=ic status --all
----

== dfx 容器停止

使用 `+dfx canister stop+` 命令停止当前在 {platform} 或本地容器执行环境上运行的容器。

在大多数情况下，您运行此命令以正确终止任何挂起的请求，这是升级容器的先决条件。

请注意，您只能从项目目录结构中运行此命令。
例如，如果您的项目名称是 `+hello_world+`，那么您当前的工作目录必须是 `+hello_world+` 顶级项目目录或其子目录之一。

=== 基本用法

[source,bash,subs="quotes"]
----
dfx canister stop [flag] [--all | _canister_name_]
----

=== 标志

您可以在 `+dfx canister stop+` 命令中使用以下可选标志。

[width="100%",cols="<31%,<69%",options="header"]
|===
|标志 |说明

|`+-h+`, `+--help+` |显示使用信息。

|`+-V+`, `+--version+` |显示版本信息。
|===

=== 参数

您可以在 `+dfx canister stop+` 命令中使用以下参数。

[width="100%",cols="<31%,<69%",options="header"]
|===
|参数 |描述

|`+--all+` |停止在`+dfx.json+`文件中配置的所有容器。 请注意，您必须指定 `+--all+` 或单个容器名称。

|`+canister_name+` |指定要停止的容器的名称。
请注意，您必须指定容器名称或 `+--all+` 选项。
|===

=== 例子

您可以使用 `+dfx canister stop+` 命令启动特定容器或所有容器。

要停止 `+hello_world+` 容器，可以运行以下命令：

[source,bash]
----
dfx canister stop hello_world
----

要停止您在 `+ic+` {platform} 上部署的所有容器，可以运行以下命令：

[source,bash]
----
dfx canister --network=ic stop --all
----
