= dfx 生成

使用 `+dfx generate+` 命令为支持的编程语言生成容器类型声明。
目前，`+dfx generate+` 支持四种语言：Motoko、Candid、JavaScript 和 TypeScript。

Y您可以使用此命令为所有容器生成类型声明
在项目的 `+dfx.json+` 配置文件或特定容器中为项目定义的。

请注意，您只能从项目目录结构中运行此命令。
例如，如果您的项目名称是 `+hello_world+`，那么您当前的工作目录必须是 `+hello_world+` 顶级项目目录或其子目录之一。

`+dfx generate+` 命令在 `+dfx.json+` 配置文件中的容器的 `+declarations+` 部分下查找配置。

== 基本用法

[source,bash]
----
dfx generate [canister_name]
----

== 标志

您可以在 `+dfx generate+` 命令中使用以下可选标志。

[width="100%",cols="<32%,<68%",options="header"]
|===
|标志 |说明

|`+-h+`, `+--help+` |Displays usage information.

|`+-V+`, `+--version+` |Displays version information.
|===

== 参数

您可以为 `+dfx generate+` 命令指定以下参数。

[width="100%",cols="<36%,<64%",options="header"]
|===

|参数 |描述

|`+canister_name+` |指定要为其生成类型声明的容器的名称。
容器名称必须与您在项目的 `+dfx.json+` 配置文件的 `+canisters+` 部分中配置的至少一个名称匹配。
如果您不指定此参数，`+dfx generate+` 将为在 `+dfx.json+` 中声明的所有容器生成类型声明。

|===

== 配置

`+dfx generate+` 的行为由 `+dfx.json+` 配置文件控制。
在 `+dfx.json+` → `+canisters+` → `+<canister_name>+` 下，您可以添加 `+declarations+` 部分。
在本节中，您可以指定以下字段：

[width="100%",cols="<32%,<68%",options="header"]
|===
|字段 |描述

|`+output+` |放置容器声明的目录。 默认为 `+src/declarations/<canister_name>+`。

|`+bindings+` |生成类型声明的语言列表。 选项是`+"js"、"ts"、"did"、"mo"+`。 默认为 `+["js", "ts", "did"]+`。

|`+env_override+` |将替换`+src/dfx/assets/language_bindings/canister.js+`模板中的`+process.env.{canister_name_uppercase}_CANISTER_ID+`的字符串。

|===

Outputs from `+dfx generate+`:

[width="100%",cols="<32%,<68%",options="header"]
|===
|语言 |文件

|`+JavaScript(js)+` |`+index.js+` and `+<canister_name>.did.js+`

|`+TypeScript(ts)+` |`+<canister_name>.did.ts+`

|`+Candid(did)+` |`+<canister_name>.did+`

|`+Motoko(mo)+` |`+<canister_name>.mo+`
|===

== 例子

[source,json]
----
包含::example$sample-generate-dfx.json[]
----

请注意，文件系统上程序的文件名和路径必须与 `+dfx.json+` 配置文件中指定的信息匹配。

在这个例子中，`+hello_world+` 容器本身是用 Motoko 编写的。 `+declarations+` 部分指定将生成所有四种语言的类型声明并将其存储在 `+src/declarations/+` 中。

[source,bash]
----
dfx generate hello_world
----

由于 `+dfx.json+` 中只有一个容器，因此在不带参数的情况下调用 `+dfx generate+` 将与上述命令具有相同的效果。 如果在 `+dfx.json+` 中定义了多个容器，这将为所有定义的容器生成类型声明。

[source,bash]
----
dfx generate
----
