= dfx config

使用 `+dfx config+` 命令查看或配置当前项目的配置文件中的设置。
请注意，您只能从项目目录结构中运行此命令。
例如，如果您的项目名称是 `+hello_world+`，那么您当前的工作目录必须是 `+hello_world+` 顶级项目目录或其子目录之一。

== 基本用法

[source,bash]
----
dfx config [config_path] [value] [flag]
----

== 标志

您可以在 `+dfx config+` 命令中使用以下可选标志。

[width="100%",cols="<32%,<68%",options="header"]
|===
|标志 |说明
|`+-h+`, `+--help+` |显示使用信息。
|`+-V+`, `+--version+` |显示版本信息。
|===

== 选项

您可以在 `+dfx config+` 命令中使用以下选项。

[width="100%",cols="<32%,<68%",options="header"]
|===
|选项 |说明
|`+--format+` |指定配置文件输出的格式。
默认情况下，文件以 JSON 格式显示。
有效值为 `+json+` 和 `+text+`。
|===

== 参数

您可以为 `+dfx config+` 命令指定以下参数。

[width="100%",cols="<34%,<66%",options="header"]
|===
|参数 |描述
|`+config_path+` |指定要设置或读取的配置选项的名称。
您必须使用其周期描述的路径指定配置文件选项，以设置或读取您要更改或查看的特定选项。
如果您未指定特定配置选项的路径，该命令将显示完整的配置文件。

|`+value+` |为您正在更改的选项指定新值。
如果您未指定值，该命令将返回配置文件中选项的当前值。
|===

== 例子

您可以使用 `+dfx config+` 命令更改配置设置，例如默认输出目录的位置或主程序文件的名称。

例如，要将默认构建输出目录从 `+canisters+` 更改为 `+staging+`，可以运行以下命令：

[source,bash]
----
dfx config defaults.build.output "staging/"
----

要查看配置设置的当前值，您可以在配置文件中指定设置的路径而不指定值。
例如：

[source,bash]
----
dfx config defaults.build.output
----

该命令返回配置选项的当前值：

[source,bash]
----
"staging/"
----

同样，您可以通过运行类似于以下的命令来更改主源文件的名称或本地容器执行环境的端口号：

[source,bash]
----
dfx config canisters.hello.main "src/hello_world/hello-main.mo"
dfx config networks.local.bind 127.0.0.1:5050
----

您还可以通过在运行 `+dfx config+` 命令后查看 `+dfx.json+` 配置文件来验证您的配置更改。
