= 环境变量
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

您可以使用环境变量为您的 {sdk-short-name} 执行环境配置某些属性。

本节列出了当前支持的环境变量以及如何使用它们的示例。
在大多数情况下，您可以通过在终端中执行命令或在 `.profile` 文件中添加类似于以下内容的行来设置会话的环境变量:

....
export DFX_NETWORK=ic
....

== CANISTER_CANDID_PATH_{canister.name}

使用带有“CANISTER_CANDID_PATH”前缀的环境变量来引用在项目的“dfx.json”文件中列为依赖项的容器的 Candid 描述文件的路径。

例如，如果您有一个在 `dependencies` 键下列出 `whoami` 的 `whoami_assets` 容器，则可以使用 `CANISTER_CANDID_PATH_whoami_assets` 环境变量来引用 `whoami.did` 文件的位置，该文件用于本地开发 可能:

....
$PROJECT_ROOT/.dfx/local/canisters/whoami/whoami.did
....

== CANISTER_ID_{canister.name}

使用带有 `CANISTER_ID` 前缀的环境变量来引用项目的 `dfx.json` 文件中每个容器的容器标识符。

例如，如果您有一个由 `linkedup` 和 `connectd` 容器组成的 `linkedup` 项目，则可以使用 `CANISTER_ID_linkedup` 和 `CANISTER_ID_connectd` 环境变量来引用容器标识符，例如 `ryjl3-tyaaa” -aaaaa-aaaba-cai` 和 `rrkah-fqaaa-aaaaa-aaaaq-cai` — 为您的项目创建。

== DFX_CONFIG_ROOT

使用 `+DFX_CONFIG_ROOT+` 环境变量指定不同的位置来存储 `+dfx+` 的 `+.cache+` 和 `+.config+` 子目录。

默认情况下，`+.cache+` 和 `+.config+` 目录位于开发环境的主目录中。
例如，在 macOS 上，默认位置在 `+/Users/<YOUR-USER-NAME>+` 目录中。
使用 `+DFX_CONFIG_ROOT+` 环境变量为这些目录指定不同的位置。

....
DFX_CONFIG_ROOT=~/ic-root
....

== DFX_INSTALLATION_ROOT

如果您不使用操作系统的默认位置，请使用 `+DFX_INSTALLATION_ROOT+` 环境变量为 `+dfx+` 二进制文件指定不同的位置。

`+.cache/dfinity/uninstall.sh+` 脚本使用这个环境变量来识别你的 {sdk-short-name} 安装的根目录。

== DFX_VERSION

使用 `+DFX_VERSION+` 环境变量来标识您要安装的 {sdk-short-name} 的特定版本。

....
DFX_VERSION=0.9.2 sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
....
